// Code generated by ent, DO NOT EDIT.

package session

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldBusinessID holds the string denoting the business_id field in the database.
	FieldBusinessID = "business_id"
	// FieldBusinessType holds the string denoting the business_type field in the database.
	FieldBusinessType = "business_type"
	// FieldBusinessMeta holds the string denoting the business_meta field in the database.
	FieldBusinessMeta = "business_meta"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldHeartbeatInterval holds the string denoting the heartbeat_interval field in the database.
	FieldHeartbeatInterval = "heartbeat_interval"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldLockedBy holds the string denoting the locked_by field in the database.
	FieldLockedBy = "locked_by"
	// FieldLockedAt holds the string denoting the locked_at field in the database.
	FieldLockedAt = "locked_at"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the session in the database.
	Table = "sessions"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "session_messages"
	// MessagesInverseTable is the table name for the SessionMessage entity.
	// It exists in this package in order to avoid circular dependency with the "sessionmessage" package.
	MessagesInverseTable = "session_messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "session_id"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldUserID,
	FieldUsername,
	FieldBusinessID,
	FieldBusinessType,
	FieldBusinessMeta,
	FieldMode,
	FieldHeartbeatInterval,
	FieldSummary,
	FieldLockedBy,
	FieldLockedAt,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID int64
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultBusinessID holds the default value on creation for the "business_id" field.
	DefaultBusinessID string
	// DefaultBusinessType holds the default value on creation for the "business_type" field.
	DefaultBusinessType string
	// DefaultBusinessMeta holds the default value on creation for the "business_meta" field.
	DefaultBusinessMeta func() map[string]interface{}
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// DefaultHeartbeatInterval holds the default value on creation for the "heartbeat_interval" field.
	DefaultHeartbeatInterval int
	// DefaultSummary holds the default value on creation for the "summary" field.
	DefaultSummary string
	// DefaultLockedBy holds the default value on creation for the "locked_by" field.
	DefaultLockedBy string
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive Status = "active"
	StatusIdle   Status = "idle"
	StatusClosed Status = "closed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusIdle, StatusClosed:
		return nil
	default:
		return fmt.Errorf("session: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Session queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByBusinessID orders the results by the business_id field.
func ByBusinessID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessID, opts...).ToFunc()
}

// ByBusinessType orders the results by the business_type field.
func ByBusinessType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessType, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByHeartbeatInterval orders the results by the heartbeat_interval field.
func ByHeartbeatInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatInterval, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByLockedBy orders the results by the locked_by field.
func ByLockedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedBy, opts...).ToFunc()
}

// ByLockedAt orders the results by the locked_at field.
func ByLockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedAt, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
