// Code generated by ent, DO NOT EDIT.

package session

import (
	"acp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserID, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUsername, v))
}

// BusinessID applies equality check predicate on the "business_id" field. It's identical to BusinessIDEQ.
func BusinessID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldBusinessID, v))
}

// BusinessType applies equality check predicate on the "business_type" field. It's identical to BusinessTypeEQ.
func BusinessType(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldBusinessType, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldMode, v))
}

// HeartbeatInterval applies equality check predicate on the "heartbeat_interval" field. It's identical to HeartbeatIntervalEQ.
func HeartbeatInterval(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldHeartbeatInterval, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSummary, v))
}

// LockedBy applies equality check predicate on the "locked_by" field. It's identical to LockedByEQ.
func LockedBy(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLockedBy, v))
}

// LockedAt applies equality check predicate on the "locked_at" field. It's identical to LockedAtEQ.
func LockedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLockedAt, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUpdateTime, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldStatus, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldUserID))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldUsername, v))
}

// BusinessIDEQ applies the EQ predicate on the "business_id" field.
func BusinessIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldBusinessID, v))
}

// BusinessIDNEQ applies the NEQ predicate on the "business_id" field.
func BusinessIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldBusinessID, v))
}

// BusinessIDIn applies the In predicate on the "business_id" field.
func BusinessIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldBusinessID, vs...))
}

// BusinessIDNotIn applies the NotIn predicate on the "business_id" field.
func BusinessIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldBusinessID, vs...))
}

// BusinessIDGT applies the GT predicate on the "business_id" field.
func BusinessIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldBusinessID, v))
}

// BusinessIDGTE applies the GTE predicate on the "business_id" field.
func BusinessIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldBusinessID, v))
}

// BusinessIDLT applies the LT predicate on the "business_id" field.
func BusinessIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldBusinessID, v))
}

// BusinessIDLTE applies the LTE predicate on the "business_id" field.
func BusinessIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldBusinessID, v))
}

// BusinessIDContains applies the Contains predicate on the "business_id" field.
func BusinessIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldBusinessID, v))
}

// BusinessIDHasPrefix applies the HasPrefix predicate on the "business_id" field.
func BusinessIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldBusinessID, v))
}

// BusinessIDHasSuffix applies the HasSuffix predicate on the "business_id" field.
func BusinessIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldBusinessID, v))
}

// BusinessIDIsNil applies the IsNil predicate on the "business_id" field.
func BusinessIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldBusinessID))
}

// BusinessIDNotNil applies the NotNil predicate on the "business_id" field.
func BusinessIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldBusinessID))
}

// BusinessIDEqualFold applies the EqualFold predicate on the "business_id" field.
func BusinessIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldBusinessID, v))
}

// BusinessIDContainsFold applies the ContainsFold predicate on the "business_id" field.
func BusinessIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldBusinessID, v))
}

// BusinessTypeEQ applies the EQ predicate on the "business_type" field.
func BusinessTypeEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldBusinessType, v))
}

// BusinessTypeNEQ applies the NEQ predicate on the "business_type" field.
func BusinessTypeNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldBusinessType, v))
}

// BusinessTypeIn applies the In predicate on the "business_type" field.
func BusinessTypeIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldBusinessType, vs...))
}

// BusinessTypeNotIn applies the NotIn predicate on the "business_type" field.
func BusinessTypeNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldBusinessType, vs...))
}

// BusinessTypeGT applies the GT predicate on the "business_type" field.
func BusinessTypeGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldBusinessType, v))
}

// BusinessTypeGTE applies the GTE predicate on the "business_type" field.
func BusinessTypeGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldBusinessType, v))
}

// BusinessTypeLT applies the LT predicate on the "business_type" field.
func BusinessTypeLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldBusinessType, v))
}

// BusinessTypeLTE applies the LTE predicate on the "business_type" field.
func BusinessTypeLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldBusinessType, v))
}

// BusinessTypeContains applies the Contains predicate on the "business_type" field.
func BusinessTypeContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldBusinessType, v))
}

// BusinessTypeHasPrefix applies the HasPrefix predicate on the "business_type" field.
func BusinessTypeHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldBusinessType, v))
}

// BusinessTypeHasSuffix applies the HasSuffix predicate on the "business_type" field.
func BusinessTypeHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldBusinessType, v))
}

// BusinessTypeIsNil applies the IsNil predicate on the "business_type" field.
func BusinessTypeIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldBusinessType))
}

// BusinessTypeNotNil applies the NotNil predicate on the "business_type" field.
func BusinessTypeNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldBusinessType))
}

// BusinessTypeEqualFold applies the EqualFold predicate on the "business_type" field.
func BusinessTypeEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldBusinessType, v))
}

// BusinessTypeContainsFold applies the ContainsFold predicate on the "business_type" field.
func BusinessTypeContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldBusinessType, v))
}

// BusinessMetaIsNil applies the IsNil predicate on the "business_meta" field.
func BusinessMetaIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldBusinessMeta))
}

// BusinessMetaNotNil applies the NotNil predicate on the "business_meta" field.
func BusinessMetaNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldBusinessMeta))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldMode, v))
}

// HeartbeatIntervalEQ applies the EQ predicate on the "heartbeat_interval" field.
func HeartbeatIntervalEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldHeartbeatInterval, v))
}

// HeartbeatIntervalNEQ applies the NEQ predicate on the "heartbeat_interval" field.
func HeartbeatIntervalNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldHeartbeatInterval, v))
}

// HeartbeatIntervalIn applies the In predicate on the "heartbeat_interval" field.
func HeartbeatIntervalIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldHeartbeatInterval, vs...))
}

// HeartbeatIntervalNotIn applies the NotIn predicate on the "heartbeat_interval" field.
func HeartbeatIntervalNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldHeartbeatInterval, vs...))
}

// HeartbeatIntervalGT applies the GT predicate on the "heartbeat_interval" field.
func HeartbeatIntervalGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldHeartbeatInterval, v))
}

// HeartbeatIntervalGTE applies the GTE predicate on the "heartbeat_interval" field.
func HeartbeatIntervalGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldHeartbeatInterval, v))
}

// HeartbeatIntervalLT applies the LT predicate on the "heartbeat_interval" field.
func HeartbeatIntervalLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldHeartbeatInterval, v))
}

// HeartbeatIntervalLTE applies the LTE predicate on the "heartbeat_interval" field.
func HeartbeatIntervalLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldHeartbeatInterval, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldSummary, v))
}

// LockedByEQ applies the EQ predicate on the "locked_by" field.
func LockedByEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLockedBy, v))
}

// LockedByNEQ applies the NEQ predicate on the "locked_by" field.
func LockedByNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldLockedBy, v))
}

// LockedByIn applies the In predicate on the "locked_by" field.
func LockedByIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldLockedBy, vs...))
}

// LockedByNotIn applies the NotIn predicate on the "locked_by" field.
func LockedByNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldLockedBy, vs...))
}

// LockedByGT applies the GT predicate on the "locked_by" field.
func LockedByGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldLockedBy, v))
}

// LockedByGTE applies the GTE predicate on the "locked_by" field.
func LockedByGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldLockedBy, v))
}

// LockedByLT applies the LT predicate on the "locked_by" field.
func LockedByLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldLockedBy, v))
}

// LockedByLTE applies the LTE predicate on the "locked_by" field.
func LockedByLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldLockedBy, v))
}

// LockedByContains applies the Contains predicate on the "locked_by" field.
func LockedByContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldLockedBy, v))
}

// LockedByHasPrefix applies the HasPrefix predicate on the "locked_by" field.
func LockedByHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldLockedBy, v))
}

// LockedByHasSuffix applies the HasSuffix predicate on the "locked_by" field.
func LockedByHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldLockedBy, v))
}

// LockedByIsNil applies the IsNil predicate on the "locked_by" field.
func LockedByIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldLockedBy))
}

// LockedByNotNil applies the NotNil predicate on the "locked_by" field.
func LockedByNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldLockedBy))
}

// LockedByEqualFold applies the EqualFold predicate on the "locked_by" field.
func LockedByEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldLockedBy, v))
}

// LockedByContainsFold applies the ContainsFold predicate on the "locked_by" field.
func LockedByContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldLockedBy, v))
}

// LockedAtEQ applies the EQ predicate on the "locked_at" field.
func LockedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLockedAt, v))
}

// LockedAtNEQ applies the NEQ predicate on the "locked_at" field.
func LockedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldLockedAt, v))
}

// LockedAtIn applies the In predicate on the "locked_at" field.
func LockedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldLockedAt, vs...))
}

// LockedAtNotIn applies the NotIn predicate on the "locked_at" field.
func LockedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldLockedAt, vs...))
}

// LockedAtGT applies the GT predicate on the "locked_at" field.
func LockedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldLockedAt, v))
}

// LockedAtGTE applies the GTE predicate on the "locked_at" field.
func LockedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldLockedAt, v))
}

// LockedAtLT applies the LT predicate on the "locked_at" field.
func LockedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldLockedAt, v))
}

// LockedAtLTE applies the LTE predicate on the "locked_at" field.
func LockedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldLockedAt, v))
}

// LockedAtIsNil applies the IsNil predicate on the "locked_at" field.
func LockedAtIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldLockedAt))
}

// LockedAtNotNil applies the NotNil predicate on the "locked_at" field.
func LockedAtNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldLockedAt))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUpdateTime, v))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.SessionMessage) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
