package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"sync"
	"time"

	"github.com/coder/acp-go-sdk"
	"github.com/cloudwego/eino/schema"
)

// =========================================================================
// Agent — implements acp.Agent, handles one ACP connection
// =========================================================================

var _ acp.Agent = (*Agent)(nil)

type Agent struct {
	cfg         Config
	llmProvider LLMConfigProvider
	modelInfo   ModelInfoProvider
	conn        *acp.AgentSideConnection
	sessionID   string
	sessionMu   sync.Mutex
}

func NewAgent(cfg Config, llmProvider LLMConfigProvider, modelInfo ModelInfoProvider) *Agent {
	return &Agent{
		cfg:         cfg,
		llmProvider: llmProvider,
		modelInfo:   modelInfo,
	}
}

func (a *Agent) SetConnection(conn *acp.AgentSideConnection) {
	a.conn = conn
}

func (a *Agent) getSession() string {
	a.sessionMu.Lock()
	defer a.sessionMu.Unlock()
	return a.sessionID
}

func (a *Agent) setSession(id string) {
	a.sessionMu.Lock()
	defer a.sessionMu.Unlock()
	a.sessionID = id
}

func (a *Agent) clearSession() {
	a.sessionMu.Lock()
	defer a.sessionMu.Unlock()
	a.sessionID = ""
}

// OnDisconnect marks the current session as idle when the connection drops.
func (a *Agent) OnDisconnect(ctx context.Context) {
	sid := a.getSession()
	if sid == "" {
		return
	}
	a.clearSession()
	sm := GetSessionManager()
	if s, ok := sm.GetCached(sid); ok && s.Status() == "active" {
		sm.MarkIdle(ctx, sid)
	}
}

// =========================================================================
// acp.Agent methods
// =========================================================================

func (a *Agent) Initialize(ctx context.Context, params acp.InitializeRequest) (acp.InitializeResponse, error) {
	return acp.InitializeResponse{
		ProtocolVersion: acp.ProtocolVersionNumber,
		AgentCapabilities: acp.AgentCapabilities{
			LoadSession: false, // merged into session/resume
			McpCapabilities: acp.McpCapabilities{
				Http: true,
				Sse:  true,
			},
			PromptCapabilities: acp.PromptCapabilities{
				Image:           true,
				Audio:           false,
				EmbeddedContext: false,
			},
			SessionCapabilities: acp.SessionCapabilities{
				Close:  &acp.SessionCloseCapabilities{},
				List:   &acp.SessionListCapabilities{},
				Resume: &acp.SessionResumeCapabilities{},
			},
		},
	}, nil
}

func (a *Agent) Authenticate(ctx context.Context, params acp.AuthenticateRequest) (acp.AuthenticateResponse, error) {
	return acp.AuthenticateResponse{}, nil
}

func (a *Agent) NewSession(ctx context.Context, params acp.NewSessionRequest) (acp.NewSessionResponse, error) {
	// Get LLM config via provider
	llmCfg, err := a.llmProvider.GetConfig(ctx)
	if err != nil {
		return acp.NewSessionResponse{}, fmt.Errorf("get LLM config: %w", err)
	}

	// Get context window
	contextWindow, err := a.modelInfo.GetContextWindow(ctx, llmCfg.Model)
	if err != nil {
		contextWindow = 131072 // fallback
	}

	// Extract params from request meta
	systemPrompt := ""
	if v, ok := params.Meta["system_prompt"].(string); ok && v != "" {
		systemPrompt = v
	}

	mode := "agent"
	if v, ok := params.Meta["mode"].(string); ok && v != "" {
		mode = v
	}

	maxIterations := 20
	if v, ok := params.Meta["max_iterations"].(float64); ok && v > 0 {
		maxIterations = int(v)
	}

	summRatio := 0.8
	if v, ok := params.Meta["summarization_trigger_ratio"].(float64); ok && v > 0 {
		summRatio = v
	}

	businessID := ""
	if v, ok := params.Meta["business_id"].(string); ok {
		businessID = v
	}
	businessType := ""
	if v, ok := params.Meta["business_type"].(string); ok {
		businessType = v
	}
	businessMeta := map[string]any{}
	if v, ok := params.Meta["business_meta"].(map[string]any); ok {
		businessMeta = v
	}

	// Create session in DB + cache (UUID generated by SessionManager)
	sm := GetSessionManager()

	// If agent already has a session, release it
	if prev := a.getSession(); prev != "" {
		sm.MarkIdle(ctx, prev)
	}

	s, err := sm.NewSession(ctx, NewSessionParams{
		Mode:                      mode,
		SummarizationTriggerRatio: summRatio,
		MaxIterations:             maxIterations,
		SystemPrompt:              systemPrompt,
		BusinessID:                businessID,
		BusinessType:              businessType,
		BusinessMeta:              businessMeta,
	})
	if err != nil {
		return acp.NewSessionResponse{}, fmt.Errorf("create session: %w", err)
	}

	// Connect MCP servers
	mcpMgr := &Manager{}
	mcpTools, mcpErr := mcpMgr.Connect(ctx, params.McpServers)
	if mcpErr != nil {
		slog.Warn("some MCP servers failed to connect", "error", mcpErr)
	}

	// Build ChatModel per session
	chatModel, err := NewChatModel(ctx, llmCfg)
	if err != nil {
		mcpMgr.Close()
		return acp.NewSessionResponse{}, fmt.Errorf("create chat model: %w", err)
	}

	// Build ChatModelAgent with middleware
	cmAgent, err := buildSessionAgent(ctx, chatModel, mcpTools, s, contextWindow)
	if err != nil {
		mcpMgr.Close()
		return acp.NewSessionResponse{}, fmt.Errorf("build agent: %w", err)
	}

	s.SetMCAgent(cmAgent, mcpMgr)
	a.setSession(s.ID)

	slog.Info("new session created", "id", s.ID, "mode", mode)
	return acp.NewSessionResponse{SessionId: acp.SessionId(s.ID)}, nil
}

func (a *Agent) Prompt(ctx context.Context, params acp.PromptRequest) (acp.PromptResponse, error) {
	sid := string(params.SessionId)
	if sid != a.getSession() {
		return acp.PromptResponse{}, fmt.Errorf("session %s does not belong to this connection", sid)
	}

	sm := GetSessionManager()
	s, ok := sm.GetCached(sid)
	if !ok {
		return acp.PromptResponse{}, fmt.Errorf("session %s not found", sid)
	}

	// Validate status
	if s.Status() == "closed" {
		return acp.PromptResponse{}, fmt.Errorf("session %s is closed", sid)
	}
	if s.Status() == "idle" {
		return acp.PromptResponse{}, fmt.Errorf("session %s is idle, use resume to re-activate", sid)
	}

	// Acquire prompt lock (reject concurrent prompts)
	if !s.TryLockPrompt() {
		return acp.PromptResponse{}, fmt.Errorf("session %s is busy with another prompt", sid)
	}
	defer s.UnlockPrompt()

	ctx, cancel := context.WithCancel(ctx)
	s.SetCancel(cancel)
	defer cancel()

	conn := a.conn
	if conn == nil {
		return acp.PromptResponse{}, fmt.Errorf("agent connection not set")
	}

	ctx = ContextWithACP(ctx, conn, acp.SessionId(sid))

	userMsg := ContentBlocksToMessage(params.Prompt)
	s.AppendMessages(userMsg)

	if err := runReAct(ctx, conn, s); err != nil {
		slog.Error("prompt execution failed", "error", err)
		return acp.PromptResponse{}, err
	}

	return acp.PromptResponse{StopReason: acp.StopReasonEndTurn}, nil
}

func (a *Agent) ResumeSession(ctx context.Context, params acp.ResumeSessionRequest) (acp.ResumeSessionResponse, error) {
	sid := string(params.SessionId)
	sm := GetSessionManager()

	// If this is already our session, no-op
	if sid == a.getSession() {
		if s, ok := sm.GetCached(sid); ok && s.Status() == "active" {
			return acp.ResumeSessionResponse{}, nil
		}
	}

	// If the session is active in another connection, reject
	if s, ok := sm.GetCached(sid); ok {
		if s.Status() == "closed" {
			return acp.ResumeSessionResponse{}, fmt.Errorf("session %s is closed", sid)
		}
		if s.Status() == "active" {
			return acp.ResumeSessionResponse{}, fmt.Errorf("session %s is active in another connection", sid)
		}
	}

	// Release current session if any
	if prev := a.getSession(); prev != "" {
		sm.MarkIdle(ctx, prev)
	}

	// Resume from DB
	s, err := sm.Resume(ctx, sid, nil)
	if err != nil {
		return acp.ResumeSessionResponse{}, fmt.Errorf("resume session: %w", err)
	}
	a.setSession(sid)

	// Reconnect MCP if servers provided via meta
	if servers, ok := params.Meta["mcp_servers"].([]any); ok && len(servers) > 0 {
		mcpMgr := &Manager{}
		data, _ := json.Marshal(servers)
		var acpServers []acp.McpServer
		if json.Unmarshal(data, &acpServers) == nil {
			_, _ = mcpMgr.Connect(ctx, acpServers)
			s.SetMCAgent(nil, mcpMgr)
		}
	}

	// Get LLM config
	llmCfg, err := a.llmProvider.GetConfig(ctx)
	if err != nil {
		return acp.ResumeSessionResponse{}, fmt.Errorf("get LLM config: %w", err)
	}
	contextWindow, _ := a.modelInfo.GetContextWindow(ctx, llmCfg.Model)
	if contextWindow == 0 {
		contextWindow = 131072
	}

	// Build new ChatModel per session
	chatModel, err := NewChatModel(ctx, llmCfg)
	if err != nil {
		return acp.ResumeSessionResponse{}, fmt.Errorf("create chat model: %w", err)
	}

	// Build ChatModelAgent
	cmAgent, err := buildSessionAgent(ctx, chatModel, nil, s, contextWindow)
	if err != nil {
		return acp.ResumeSessionResponse{}, fmt.Errorf("build agent: %w", err)
	}

	// Get existing MCP manager if any
	mgr := s.GetMCPManager()
	s.SetMCAgent(cmAgent, mgr)

	conn := a.conn
	if conn == nil {
		return acp.ResumeSessionResponse{}, fmt.Errorf("agent connection not set")
	}

	ctx = ContextWithACP(ctx, conn, acp.SessionId(sid))

	// If a prompt was provided, run ReAct loop
	if prompt, ok := params.Meta["prompt"].(string); ok && prompt != "" {
		userMsg := schema.UserMessage(prompt)
		s.AppendMessages(userMsg)

		if err := runReAct(ctx, conn, s); err != nil {
			return acp.ResumeSessionResponse{}, err
		}
	}

	return acp.ResumeSessionResponse{}, nil
}

func (a *Agent) CloseSession(ctx context.Context, params acp.CloseSessionRequest) (acp.CloseSessionResponse, error) {
	sid := string(params.SessionId)
	sm := GetSessionManager()
	s, ok := sm.GetCached(sid)
	if !ok {
		return acp.CloseSessionResponse{}, fmt.Errorf("session %s not found", sid)
	}

	if s.Status() == "closed" {
		return acp.CloseSessionResponse{}, fmt.Errorf("session %s is already closed", sid)
	}

	if err := sm.Close(ctx, sid); err != nil {
		return acp.CloseSessionResponse{}, fmt.Errorf("close session: %w", err)
	}

	if a.getSession() == sid {
		a.clearSession()
	}

	return acp.CloseSessionResponse{}, nil
}

func (a *Agent) ListSessions(ctx context.Context, params acp.ListSessionsRequest) (acp.ListSessionsResponse, error) {
	sm := GetSessionManager()
	metas, err := sm.List(ctx)
	if err != nil {
		return acp.ListSessionsResponse{}, fmt.Errorf("list sessions: %w", err)
	}

	items := make([]acp.SessionInfo, 0, len(metas))
	for _, m := range metas {
		updatedAt := m.UpdateTime.Format(time.RFC3339)
		title := fmt.Sprintf("%s@%s", m.Username, m.BusinessType)
		items = append(items, acp.SessionInfo{
			SessionId: acp.SessionId(m.ID),
			Cwd:       "/",
			Title:     &title,
			UpdatedAt: &updatedAt,
		})
	}
	return acp.ListSessionsResponse{Sessions: items}, nil
}

func (a *Agent) Cancel(ctx context.Context, params acp.CancelNotification) error {
	sid := string(params.SessionId)
	sm := GetSessionManager()
	if s, ok := sm.GetCached(sid); ok {
		s.Cancel()
	}
	return nil
}

func (a *Agent) SetSessionConfigOption(ctx context.Context, params acp.SetSessionConfigOptionRequest) (acp.SetSessionConfigOptionResponse, error) {
	return acp.SetSessionConfigOptionResponse{}, nil
}

func (a *Agent) SetSessionMode(ctx context.Context, params acp.SetSessionModeRequest) (acp.SetSessionModeResponse, error) {
	// Mode is immutable at creation — return error
	return acp.SetSessionModeResponse{}, fmt.Errorf("session mode is immutable after creation")
}

func (a *Agent) Logout(ctx context.Context, params acp.LogoutRequest) (acp.LogoutResponse, error) {
	return acp.LogoutResponse{}, nil
}

// =========================================================================
// ACP context helpers (injected into context for tool access)
// =========================================================================

type acpContextKey struct{}

type acpContext struct {
	Conn      *acp.AgentSideConnection
	SessionID acp.SessionId
}

func ContextWithACP(ctx context.Context, conn *acp.AgentSideConnection, sessionID acp.SessionId) context.Context {
	return context.WithValue(ctx, acpContextKey{}, &acpContext{
		Conn:      conn,
		SessionID: sessionID,
	})
}

func getACPContext(ctx context.Context) (*acp.AgentSideConnection, acp.SessionId) {
	if v, ok := ctx.Value(acpContextKey{}).(*acpContext); ok {
		return v.Conn, v.SessionID
	}
	return nil, ""
}

// =========================================================================
// ACP ContentBlock -> eino Message conversion
// =========================================================================

func ContentBlocksToMessage(blocks []acp.ContentBlock) *schema.Message {
	var textParts []string
	var imageParts []schema.MessageInputPart

	for _, block := range blocks {
		switch {
		case block.Text != nil:
			textParts = append(textParts, block.Text.Text)
		case block.Image != nil:
			imageParts = append(imageParts, schema.MessageInputPart{
				Type: schema.ChatMessagePartTypeImageURL,
				Image: &schema.MessageInputImage{
					MessagePartCommon: schema.MessagePartCommon{
						Base64Data: &block.Image.Data,
						MIMEType:   block.Image.MimeType,
					},
				},
			})
		case block.ResourceLink != nil:
			textParts = append(textParts,
				fmt.Sprintf("[Resource: %s](%s)", block.ResourceLink.Name, block.ResourceLink.Uri))
		case block.Resource != nil:
			if block.Resource.Resource.TextResourceContents != nil {
				textParts = append(textParts, block.Resource.Resource.TextResourceContents.Text)
			}
		case block.Audio != nil:
			textParts = append(textParts, "[Audio content attached]")
		}
	}

	textContent := strings.Join(textParts, "\n")

	if len(imageParts) > 0 {
		parts := make([]schema.MessageInputPart, 0, len(imageParts)+1)
		if textContent != "" {
			parts = append(parts, schema.MessageInputPart{
				Type: schema.ChatMessagePartTypeText,
				Text: textContent,
			})
		}
		parts = append(parts, imageParts...)
		return &schema.Message{
			Role:                  schema.User,
			UserInputMultiContent: parts,
		}
	}

	return schema.UserMessage(textContent)
}
