// Code generated by ent, DO NOT EDIT.

package sessionmessage

import (
	"acp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldSessionID, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldSeq, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldContent, v))
}

// ToolCallID applies equality check predicate on the "tool_call_id" field. It's identical to ToolCallIDEQ.
func ToolCallID(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldToolCallID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldCreateTime, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldContainsFold(FieldSessionID, v))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLTE(FieldSeq, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldRole, vs...))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldContainsFold(FieldContent, v))
}

// ToolCallsIsNil applies the IsNil predicate on the "tool_calls" field.
func ToolCallsIsNil() predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIsNull(FieldToolCalls))
}

// ToolCallsNotNil applies the NotNil predicate on the "tool_calls" field.
func ToolCallsNotNil() predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotNull(FieldToolCalls))
}

// ToolCallIDEQ applies the EQ predicate on the "tool_call_id" field.
func ToolCallIDEQ(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldToolCallID, v))
}

// ToolCallIDNEQ applies the NEQ predicate on the "tool_call_id" field.
func ToolCallIDNEQ(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldToolCallID, v))
}

// ToolCallIDIn applies the In predicate on the "tool_call_id" field.
func ToolCallIDIn(vs ...string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldToolCallID, vs...))
}

// ToolCallIDNotIn applies the NotIn predicate on the "tool_call_id" field.
func ToolCallIDNotIn(vs ...string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldToolCallID, vs...))
}

// ToolCallIDGT applies the GT predicate on the "tool_call_id" field.
func ToolCallIDGT(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGT(FieldToolCallID, v))
}

// ToolCallIDGTE applies the GTE predicate on the "tool_call_id" field.
func ToolCallIDGTE(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGTE(FieldToolCallID, v))
}

// ToolCallIDLT applies the LT predicate on the "tool_call_id" field.
func ToolCallIDLT(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLT(FieldToolCallID, v))
}

// ToolCallIDLTE applies the LTE predicate on the "tool_call_id" field.
func ToolCallIDLTE(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLTE(FieldToolCallID, v))
}

// ToolCallIDContains applies the Contains predicate on the "tool_call_id" field.
func ToolCallIDContains(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldContains(FieldToolCallID, v))
}

// ToolCallIDHasPrefix applies the HasPrefix predicate on the "tool_call_id" field.
func ToolCallIDHasPrefix(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldHasPrefix(FieldToolCallID, v))
}

// ToolCallIDHasSuffix applies the HasSuffix predicate on the "tool_call_id" field.
func ToolCallIDHasSuffix(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldHasSuffix(FieldToolCallID, v))
}

// ToolCallIDIsNil applies the IsNil predicate on the "tool_call_id" field.
func ToolCallIDIsNil() predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIsNull(FieldToolCallID))
}

// ToolCallIDNotNil applies the NotNil predicate on the "tool_call_id" field.
func ToolCallIDNotNil() predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotNull(FieldToolCallID))
}

// ToolCallIDEqualFold applies the EqualFold predicate on the "tool_call_id" field.
func ToolCallIDEqualFold(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEqualFold(FieldToolCallID, v))
}

// ToolCallIDContainsFold applies the ContainsFold predicate on the "tool_call_id" field.
func ToolCallIDContainsFold(v string) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldContainsFold(FieldToolCallID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SessionMessage {
	return predicate.SessionMessage(sql.FieldLTE(FieldCreateTime, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.SessionMessage {
	return predicate.SessionMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.SessionMessage {
	return predicate.SessionMessage(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SessionMessage) predicate.SessionMessage {
	return predicate.SessionMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SessionMessage) predicate.SessionMessage {
	return predicate.SessionMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SessionMessage) predicate.SessionMessage {
	return predicate.SessionMessage(sql.NotPredicates(p))
}
