// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "idle", "closed"}, Default: "active"},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "username", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "business_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "business_type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "business_meta", Type: field.TypeJSON, Nullable: true},
		{Name: "mode", Type: field.TypeString, Default: "agent"},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_status",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[1]},
			},
			{
				Name:    "session_user_id",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[2]},
			},
			{
				Name:    "session_business_id_business_type",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[4], SessionsColumns[5]},
			},
		},
	}
	// SessionMessagesColumns holds the columns for the "session_messages" table.
	SessionMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "seq", Type: field.TypeInt},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"system", "user", "assistant", "tool"}},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "tool_calls", Type: field.TypeJSON, Nullable: true},
		{Name: "tool_call_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString},
	}
	// SessionMessagesTable holds the schema information for the "session_messages" table.
	SessionMessagesTable = &schema.Table{
		Name:       "session_messages",
		Columns:    SessionMessagesColumns,
		PrimaryKey: []*schema.Column{SessionMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "session_messages_sessions_messages",
				Columns:    []*schema.Column{SessionMessagesColumns[7]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sessionmessage_session_id_seq",
				Unique:  true,
				Columns: []*schema.Column{SessionMessagesColumns[7], SessionMessagesColumns[1]},
			},
			{
				Name:    "sessionmessage_session_id",
				Unique:  false,
				Columns: []*schema.Column{SessionMessagesColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SessionsTable,
		SessionMessagesTable,
	}
)

func init() {
	SessionMessagesTable.ForeignKeys[0].RefTable = SessionsTable
}
