// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/predicate"
	"acp/ent/schema"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSession        = "Session"
	TypeSessionMessage = "SessionMessage"
)

// SessionMutation represents an operation that mutates the Session nodes in the graph.
type SessionMutation struct {
	config
	op              Op
	typ             string
	id              *string
	status          *session.Status
	user_id         *int64
	adduser_id      *int64
	username        *string
	business_id     *string
	business_type   *string
	business_meta   *map[string]interface{}
	mode            *string
	summary         *string
	create_time     *time.Time
	update_time     *time.Time
	clearedFields   map[string]struct{}
	messages        map[int64]struct{}
	removedmessages map[int64]struct{}
	clearedmessages bool
	done            bool
	oldValue        func(context.Context) (*Session, error)
	predicates      []predicate.Session
}

var _ ent.Mutation = (*SessionMutation)(nil)

// sessionOption allows management of the mutation configuration using functional options.
type sessionOption func(*SessionMutation)

// newSessionMutation creates new mutation for the Session entity.
func newSessionMutation(c config, op Op, opts ...sessionOption) *SessionMutation {
	m := &SessionMutation{
		config:        c,
		op:            op,
		typ:           TypeSession,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSessionID sets the ID field of the mutation.
func withSessionID(id string) sessionOption {
	return func(m *SessionMutation) {
		var (
			err   error
			once  sync.Once
			value *Session
		)
		m.oldValue = func(ctx context.Context) (*Session, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Session.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSession sets the old Session of the mutation.
func withSession(node *Session) sessionOption {
	return func(m *SessionMutation) {
		m.oldValue = func(context.Context) (*Session, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SessionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SessionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Session entities.
func (m *SessionMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SessionMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SessionMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Session.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetStatus sets the "status" field.
func (m *SessionMutation) SetStatus(s session.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SessionMutation) Status() (r session.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldStatus(ctx context.Context) (v session.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SessionMutation) ResetStatus() {
	m.status = nil
}

// SetUserID sets the "user_id" field.
func (m *SessionMutation) SetUserID(i int64) {
	m.user_id = &i
	m.adduser_id = nil
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *SessionMutation) UserID() (r int64, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldUserID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// AddUserID adds i to the "user_id" field.
func (m *SessionMutation) AddUserID(i int64) {
	if m.adduser_id != nil {
		*m.adduser_id += i
	} else {
		m.adduser_id = &i
	}
}

// AddedUserID returns the value that was added to the "user_id" field in this mutation.
func (m *SessionMutation) AddedUserID() (r int64, exists bool) {
	v := m.adduser_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearUserID clears the value of the "user_id" field.
func (m *SessionMutation) ClearUserID() {
	m.user_id = nil
	m.adduser_id = nil
	m.clearedFields[session.FieldUserID] = struct{}{}
}

// UserIDCleared returns if the "user_id" field was cleared in this mutation.
func (m *SessionMutation) UserIDCleared() bool {
	_, ok := m.clearedFields[session.FieldUserID]
	return ok
}

// ResetUserID resets all changes to the "user_id" field.
func (m *SessionMutation) ResetUserID() {
	m.user_id = nil
	m.adduser_id = nil
	delete(m.clearedFields, session.FieldUserID)
}

// SetUsername sets the "username" field.
func (m *SessionMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *SessionMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ClearUsername clears the value of the "username" field.
func (m *SessionMutation) ClearUsername() {
	m.username = nil
	m.clearedFields[session.FieldUsername] = struct{}{}
}

// UsernameCleared returns if the "username" field was cleared in this mutation.
func (m *SessionMutation) UsernameCleared() bool {
	_, ok := m.clearedFields[session.FieldUsername]
	return ok
}

// ResetUsername resets all changes to the "username" field.
func (m *SessionMutation) ResetUsername() {
	m.username = nil
	delete(m.clearedFields, session.FieldUsername)
}

// SetBusinessID sets the "business_id" field.
func (m *SessionMutation) SetBusinessID(s string) {
	m.business_id = &s
}

// BusinessID returns the value of the "business_id" field in the mutation.
func (m *SessionMutation) BusinessID() (r string, exists bool) {
	v := m.business_id
	if v == nil {
		return
	}
	return *v, true
}

// OldBusinessID returns the old "business_id" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldBusinessID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBusinessID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBusinessID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBusinessID: %w", err)
	}
	return oldValue.BusinessID, nil
}

// ClearBusinessID clears the value of the "business_id" field.
func (m *SessionMutation) ClearBusinessID() {
	m.business_id = nil
	m.clearedFields[session.FieldBusinessID] = struct{}{}
}

// BusinessIDCleared returns if the "business_id" field was cleared in this mutation.
func (m *SessionMutation) BusinessIDCleared() bool {
	_, ok := m.clearedFields[session.FieldBusinessID]
	return ok
}

// ResetBusinessID resets all changes to the "business_id" field.
func (m *SessionMutation) ResetBusinessID() {
	m.business_id = nil
	delete(m.clearedFields, session.FieldBusinessID)
}

// SetBusinessType sets the "business_type" field.
func (m *SessionMutation) SetBusinessType(s string) {
	m.business_type = &s
}

// BusinessType returns the value of the "business_type" field in the mutation.
func (m *SessionMutation) BusinessType() (r string, exists bool) {
	v := m.business_type
	if v == nil {
		return
	}
	return *v, true
}

// OldBusinessType returns the old "business_type" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldBusinessType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBusinessType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBusinessType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBusinessType: %w", err)
	}
	return oldValue.BusinessType, nil
}

// ClearBusinessType clears the value of the "business_type" field.
func (m *SessionMutation) ClearBusinessType() {
	m.business_type = nil
	m.clearedFields[session.FieldBusinessType] = struct{}{}
}

// BusinessTypeCleared returns if the "business_type" field was cleared in this mutation.
func (m *SessionMutation) BusinessTypeCleared() bool {
	_, ok := m.clearedFields[session.FieldBusinessType]
	return ok
}

// ResetBusinessType resets all changes to the "business_type" field.
func (m *SessionMutation) ResetBusinessType() {
	m.business_type = nil
	delete(m.clearedFields, session.FieldBusinessType)
}

// SetBusinessMeta sets the "business_meta" field.
func (m *SessionMutation) SetBusinessMeta(value map[string]interface{}) {
	m.business_meta = &value
}

// BusinessMeta returns the value of the "business_meta" field in the mutation.
func (m *SessionMutation) BusinessMeta() (r map[string]interface{}, exists bool) {
	v := m.business_meta
	if v == nil {
		return
	}
	return *v, true
}

// OldBusinessMeta returns the old "business_meta" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldBusinessMeta(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBusinessMeta is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBusinessMeta requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBusinessMeta: %w", err)
	}
	return oldValue.BusinessMeta, nil
}

// ClearBusinessMeta clears the value of the "business_meta" field.
func (m *SessionMutation) ClearBusinessMeta() {
	m.business_meta = nil
	m.clearedFields[session.FieldBusinessMeta] = struct{}{}
}

// BusinessMetaCleared returns if the "business_meta" field was cleared in this mutation.
func (m *SessionMutation) BusinessMetaCleared() bool {
	_, ok := m.clearedFields[session.FieldBusinessMeta]
	return ok
}

// ResetBusinessMeta resets all changes to the "business_meta" field.
func (m *SessionMutation) ResetBusinessMeta() {
	m.business_meta = nil
	delete(m.clearedFields, session.FieldBusinessMeta)
}

// SetMode sets the "mode" field.
func (m *SessionMutation) SetMode(s string) {
	m.mode = &s
}

// Mode returns the value of the "mode" field in the mutation.
func (m *SessionMutation) Mode() (r string, exists bool) {
	v := m.mode
	if v == nil {
		return
	}
	return *v, true
}

// OldMode returns the old "mode" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldMode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMode: %w", err)
	}
	return oldValue.Mode, nil
}

// ResetMode resets all changes to the "mode" field.
func (m *SessionMutation) ResetMode() {
	m.mode = nil
}

// SetSummary sets the "summary" field.
func (m *SessionMutation) SetSummary(s string) {
	m.summary = &s
}

// Summary returns the value of the "summary" field in the mutation.
func (m *SessionMutation) Summary() (r string, exists bool) {
	v := m.summary
	if v == nil {
		return
	}
	return *v, true
}

// OldSummary returns the old "summary" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldSummary(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSummary is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSummary requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSummary: %w", err)
	}
	return oldValue.Summary, nil
}

// ClearSummary clears the value of the "summary" field.
func (m *SessionMutation) ClearSummary() {
	m.summary = nil
	m.clearedFields[session.FieldSummary] = struct{}{}
}

// SummaryCleared returns if the "summary" field was cleared in this mutation.
func (m *SessionMutation) SummaryCleared() bool {
	_, ok := m.clearedFields[session.FieldSummary]
	return ok
}

// ResetSummary resets all changes to the "summary" field.
func (m *SessionMutation) ResetSummary() {
	m.summary = nil
	delete(m.clearedFields, session.FieldSummary)
}

// SetCreateTime sets the "create_time" field.
func (m *SessionMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *SessionMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *SessionMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *SessionMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *SessionMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Session entity.
// If the Session object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *SessionMutation) ResetUpdateTime() {
	m.update_time = nil
}

// AddMessageIDs adds the "messages" edge to the SessionMessage entity by ids.
func (m *SessionMutation) AddMessageIDs(ids ...int64) {
	if m.messages == nil {
		m.messages = make(map[int64]struct{})
	}
	for i := range ids {
		m.messages[ids[i]] = struct{}{}
	}
}

// ClearMessages clears the "messages" edge to the SessionMessage entity.
func (m *SessionMutation) ClearMessages() {
	m.clearedmessages = true
}

// MessagesCleared reports if the "messages" edge to the SessionMessage entity was cleared.
func (m *SessionMutation) MessagesCleared() bool {
	return m.clearedmessages
}

// RemoveMessageIDs removes the "messages" edge to the SessionMessage entity by IDs.
func (m *SessionMutation) RemoveMessageIDs(ids ...int64) {
	if m.removedmessages == nil {
		m.removedmessages = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.messages, ids[i])
		m.removedmessages[ids[i]] = struct{}{}
	}
}

// RemovedMessages returns the removed IDs of the "messages" edge to the SessionMessage entity.
func (m *SessionMutation) RemovedMessagesIDs() (ids []int64) {
	for id := range m.removedmessages {
		ids = append(ids, id)
	}
	return
}

// MessagesIDs returns the "messages" edge IDs in the mutation.
func (m *SessionMutation) MessagesIDs() (ids []int64) {
	for id := range m.messages {
		ids = append(ids, id)
	}
	return
}

// ResetMessages resets all changes to the "messages" edge.
func (m *SessionMutation) ResetMessages() {
	m.messages = nil
	m.clearedmessages = false
	m.removedmessages = nil
}

// Where appends a list predicates to the SessionMutation builder.
func (m *SessionMutation) Where(ps ...predicate.Session) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SessionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SessionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Session, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SessionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SessionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Session).
func (m *SessionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SessionMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.status != nil {
		fields = append(fields, session.FieldStatus)
	}
	if m.user_id != nil {
		fields = append(fields, session.FieldUserID)
	}
	if m.username != nil {
		fields = append(fields, session.FieldUsername)
	}
	if m.business_id != nil {
		fields = append(fields, session.FieldBusinessID)
	}
	if m.business_type != nil {
		fields = append(fields, session.FieldBusinessType)
	}
	if m.business_meta != nil {
		fields = append(fields, session.FieldBusinessMeta)
	}
	if m.mode != nil {
		fields = append(fields, session.FieldMode)
	}
	if m.summary != nil {
		fields = append(fields, session.FieldSummary)
	}
	if m.create_time != nil {
		fields = append(fields, session.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, session.FieldUpdateTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SessionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case session.FieldStatus:
		return m.Status()
	case session.FieldUserID:
		return m.UserID()
	case session.FieldUsername:
		return m.Username()
	case session.FieldBusinessID:
		return m.BusinessID()
	case session.FieldBusinessType:
		return m.BusinessType()
	case session.FieldBusinessMeta:
		return m.BusinessMeta()
	case session.FieldMode:
		return m.Mode()
	case session.FieldSummary:
		return m.Summary()
	case session.FieldCreateTime:
		return m.CreateTime()
	case session.FieldUpdateTime:
		return m.UpdateTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SessionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case session.FieldStatus:
		return m.OldStatus(ctx)
	case session.FieldUserID:
		return m.OldUserID(ctx)
	case session.FieldUsername:
		return m.OldUsername(ctx)
	case session.FieldBusinessID:
		return m.OldBusinessID(ctx)
	case session.FieldBusinessType:
		return m.OldBusinessType(ctx)
	case session.FieldBusinessMeta:
		return m.OldBusinessMeta(ctx)
	case session.FieldMode:
		return m.OldMode(ctx)
	case session.FieldSummary:
		return m.OldSummary(ctx)
	case session.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case session.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	}
	return nil, fmt.Errorf("unknown Session field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SessionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case session.FieldStatus:
		v, ok := value.(session.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case session.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case session.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case session.FieldBusinessID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBusinessID(v)
		return nil
	case session.FieldBusinessType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBusinessType(v)
		return nil
	case session.FieldBusinessMeta:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBusinessMeta(v)
		return nil
	case session.FieldMode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMode(v)
		return nil
	case session.FieldSummary:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSummary(v)
		return nil
	case session.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case session.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	}
	return fmt.Errorf("unknown Session field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SessionMutation) AddedFields() []string {
	var fields []string
	if m.adduser_id != nil {
		fields = append(fields, session.FieldUserID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SessionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case session.FieldUserID:
		return m.AddedUserID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SessionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case session.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserID(v)
		return nil
	}
	return fmt.Errorf("unknown Session numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SessionMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(session.FieldUserID) {
		fields = append(fields, session.FieldUserID)
	}
	if m.FieldCleared(session.FieldUsername) {
		fields = append(fields, session.FieldUsername)
	}
	if m.FieldCleared(session.FieldBusinessID) {
		fields = append(fields, session.FieldBusinessID)
	}
	if m.FieldCleared(session.FieldBusinessType) {
		fields = append(fields, session.FieldBusinessType)
	}
	if m.FieldCleared(session.FieldBusinessMeta) {
		fields = append(fields, session.FieldBusinessMeta)
	}
	if m.FieldCleared(session.FieldSummary) {
		fields = append(fields, session.FieldSummary)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SessionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SessionMutation) ClearField(name string) error {
	switch name {
	case session.FieldUserID:
		m.ClearUserID()
		return nil
	case session.FieldUsername:
		m.ClearUsername()
		return nil
	case session.FieldBusinessID:
		m.ClearBusinessID()
		return nil
	case session.FieldBusinessType:
		m.ClearBusinessType()
		return nil
	case session.FieldBusinessMeta:
		m.ClearBusinessMeta()
		return nil
	case session.FieldSummary:
		m.ClearSummary()
		return nil
	}
	return fmt.Errorf("unknown Session nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SessionMutation) ResetField(name string) error {
	switch name {
	case session.FieldStatus:
		m.ResetStatus()
		return nil
	case session.FieldUserID:
		m.ResetUserID()
		return nil
	case session.FieldUsername:
		m.ResetUsername()
		return nil
	case session.FieldBusinessID:
		m.ResetBusinessID()
		return nil
	case session.FieldBusinessType:
		m.ResetBusinessType()
		return nil
	case session.FieldBusinessMeta:
		m.ResetBusinessMeta()
		return nil
	case session.FieldMode:
		m.ResetMode()
		return nil
	case session.FieldSummary:
		m.ResetSummary()
		return nil
	case session.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case session.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	}
	return fmt.Errorf("unknown Session field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SessionMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.messages != nil {
		edges = append(edges, session.EdgeMessages)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SessionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case session.EdgeMessages:
		ids := make([]ent.Value, 0, len(m.messages))
		for id := range m.messages {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SessionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedmessages != nil {
		edges = append(edges, session.EdgeMessages)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SessionMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case session.EdgeMessages:
		ids := make([]ent.Value, 0, len(m.removedmessages))
		for id := range m.removedmessages {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SessionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedmessages {
		edges = append(edges, session.EdgeMessages)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SessionMutation) EdgeCleared(name string) bool {
	switch name {
	case session.EdgeMessages:
		return m.clearedmessages
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SessionMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Session unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SessionMutation) ResetEdge(name string) error {
	switch name {
	case session.EdgeMessages:
		m.ResetMessages()
		return nil
	}
	return fmt.Errorf("unknown Session edge %s", name)
}

// SessionMessageMutation represents an operation that mutates the SessionMessage nodes in the graph.
type SessionMessageMutation struct {
	config
	op               Op
	typ              string
	id               *int64
	seq              *int
	addseq           *int
	role             *sessionmessage.Role
	content          *string
	tool_calls       *[]schema.ToolCall
	appendtool_calls []schema.ToolCall
	tool_call_id     *string
	create_time      *time.Time
	clearedFields    map[string]struct{}
	session          *string
	clearedsession   bool
	done             bool
	oldValue         func(context.Context) (*SessionMessage, error)
	predicates       []predicate.SessionMessage
}

var _ ent.Mutation = (*SessionMessageMutation)(nil)

// sessionmessageOption allows management of the mutation configuration using functional options.
type sessionmessageOption func(*SessionMessageMutation)

// newSessionMessageMutation creates new mutation for the SessionMessage entity.
func newSessionMessageMutation(c config, op Op, opts ...sessionmessageOption) *SessionMessageMutation {
	m := &SessionMessageMutation{
		config:        c,
		op:            op,
		typ:           TypeSessionMessage,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSessionMessageID sets the ID field of the mutation.
func withSessionMessageID(id int64) sessionmessageOption {
	return func(m *SessionMessageMutation) {
		var (
			err   error
			once  sync.Once
			value *SessionMessage
		)
		m.oldValue = func(ctx context.Context) (*SessionMessage, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SessionMessage.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSessionMessage sets the old SessionMessage of the mutation.
func withSessionMessage(node *SessionMessage) sessionmessageOption {
	return func(m *SessionMessageMutation) {
		m.oldValue = func(context.Context) (*SessionMessage, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SessionMessageMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SessionMessageMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SessionMessage entities.
func (m *SessionMessageMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SessionMessageMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SessionMessageMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SessionMessage.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSessionID sets the "session_id" field.
func (m *SessionMessageMutation) SetSessionID(s string) {
	m.session = &s
}

// SessionID returns the value of the "session_id" field in the mutation.
func (m *SessionMessageMutation) SessionID() (r string, exists bool) {
	v := m.session
	if v == nil {
		return
	}
	return *v, true
}

// OldSessionID returns the old "session_id" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldSessionID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSessionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSessionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSessionID: %w", err)
	}
	return oldValue.SessionID, nil
}

// ResetSessionID resets all changes to the "session_id" field.
func (m *SessionMessageMutation) ResetSessionID() {
	m.session = nil
}

// SetSeq sets the "seq" field.
func (m *SessionMessageMutation) SetSeq(i int) {
	m.seq = &i
	m.addseq = nil
}

// Seq returns the value of the "seq" field in the mutation.
func (m *SessionMessageMutation) Seq() (r int, exists bool) {
	v := m.seq
	if v == nil {
		return
	}
	return *v, true
}

// OldSeq returns the old "seq" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldSeq(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeq is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeq requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeq: %w", err)
	}
	return oldValue.Seq, nil
}

// AddSeq adds i to the "seq" field.
func (m *SessionMessageMutation) AddSeq(i int) {
	if m.addseq != nil {
		*m.addseq += i
	} else {
		m.addseq = &i
	}
}

// AddedSeq returns the value that was added to the "seq" field in this mutation.
func (m *SessionMessageMutation) AddedSeq() (r int, exists bool) {
	v := m.addseq
	if v == nil {
		return
	}
	return *v, true
}

// ResetSeq resets all changes to the "seq" field.
func (m *SessionMessageMutation) ResetSeq() {
	m.seq = nil
	m.addseq = nil
}

// SetRole sets the "role" field.
func (m *SessionMessageMutation) SetRole(s sessionmessage.Role) {
	m.role = &s
}

// Role returns the value of the "role" field in the mutation.
func (m *SessionMessageMutation) Role() (r sessionmessage.Role, exists bool) {
	v := m.role
	if v == nil {
		return
	}
	return *v, true
}

// OldRole returns the old "role" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldRole(ctx context.Context) (v sessionmessage.Role, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRole is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRole requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRole: %w", err)
	}
	return oldValue.Role, nil
}

// ResetRole resets all changes to the "role" field.
func (m *SessionMessageMutation) ResetRole() {
	m.role = nil
}

// SetContent sets the "content" field.
func (m *SessionMessageMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *SessionMessageMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ClearContent clears the value of the "content" field.
func (m *SessionMessageMutation) ClearContent() {
	m.content = nil
	m.clearedFields[sessionmessage.FieldContent] = struct{}{}
}

// ContentCleared returns if the "content" field was cleared in this mutation.
func (m *SessionMessageMutation) ContentCleared() bool {
	_, ok := m.clearedFields[sessionmessage.FieldContent]
	return ok
}

// ResetContent resets all changes to the "content" field.
func (m *SessionMessageMutation) ResetContent() {
	m.content = nil
	delete(m.clearedFields, sessionmessage.FieldContent)
}

// SetToolCalls sets the "tool_calls" field.
func (m *SessionMessageMutation) SetToolCalls(sc []schema.ToolCall) {
	m.tool_calls = &sc
	m.appendtool_calls = nil
}

// ToolCalls returns the value of the "tool_calls" field in the mutation.
func (m *SessionMessageMutation) ToolCalls() (r []schema.ToolCall, exists bool) {
	v := m.tool_calls
	if v == nil {
		return
	}
	return *v, true
}

// OldToolCalls returns the old "tool_calls" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldToolCalls(ctx context.Context) (v []schema.ToolCall, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToolCalls is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToolCalls requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToolCalls: %w", err)
	}
	return oldValue.ToolCalls, nil
}

// AppendToolCalls adds sc to the "tool_calls" field.
func (m *SessionMessageMutation) AppendToolCalls(sc []schema.ToolCall) {
	m.appendtool_calls = append(m.appendtool_calls, sc...)
}

// AppendedToolCalls returns the list of values that were appended to the "tool_calls" field in this mutation.
func (m *SessionMessageMutation) AppendedToolCalls() ([]schema.ToolCall, bool) {
	if len(m.appendtool_calls) == 0 {
		return nil, false
	}
	return m.appendtool_calls, true
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (m *SessionMessageMutation) ClearToolCalls() {
	m.tool_calls = nil
	m.appendtool_calls = nil
	m.clearedFields[sessionmessage.FieldToolCalls] = struct{}{}
}

// ToolCallsCleared returns if the "tool_calls" field was cleared in this mutation.
func (m *SessionMessageMutation) ToolCallsCleared() bool {
	_, ok := m.clearedFields[sessionmessage.FieldToolCalls]
	return ok
}

// ResetToolCalls resets all changes to the "tool_calls" field.
func (m *SessionMessageMutation) ResetToolCalls() {
	m.tool_calls = nil
	m.appendtool_calls = nil
	delete(m.clearedFields, sessionmessage.FieldToolCalls)
}

// SetToolCallID sets the "tool_call_id" field.
func (m *SessionMessageMutation) SetToolCallID(s string) {
	m.tool_call_id = &s
}

// ToolCallID returns the value of the "tool_call_id" field in the mutation.
func (m *SessionMessageMutation) ToolCallID() (r string, exists bool) {
	v := m.tool_call_id
	if v == nil {
		return
	}
	return *v, true
}

// OldToolCallID returns the old "tool_call_id" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldToolCallID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToolCallID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToolCallID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToolCallID: %w", err)
	}
	return oldValue.ToolCallID, nil
}

// ClearToolCallID clears the value of the "tool_call_id" field.
func (m *SessionMessageMutation) ClearToolCallID() {
	m.tool_call_id = nil
	m.clearedFields[sessionmessage.FieldToolCallID] = struct{}{}
}

// ToolCallIDCleared returns if the "tool_call_id" field was cleared in this mutation.
func (m *SessionMessageMutation) ToolCallIDCleared() bool {
	_, ok := m.clearedFields[sessionmessage.FieldToolCallID]
	return ok
}

// ResetToolCallID resets all changes to the "tool_call_id" field.
func (m *SessionMessageMutation) ResetToolCallID() {
	m.tool_call_id = nil
	delete(m.clearedFields, sessionmessage.FieldToolCallID)
}

// SetCreateTime sets the "create_time" field.
func (m *SessionMessageMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *SessionMessageMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the SessionMessage entity.
// If the SessionMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SessionMessageMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *SessionMessageMutation) ResetCreateTime() {
	m.create_time = nil
}

// ClearSession clears the "session" edge to the Session entity.
func (m *SessionMessageMutation) ClearSession() {
	m.clearedsession = true
	m.clearedFields[sessionmessage.FieldSessionID] = struct{}{}
}

// SessionCleared reports if the "session" edge to the Session entity was cleared.
func (m *SessionMessageMutation) SessionCleared() bool {
	return m.clearedsession
}

// SessionIDs returns the "session" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// SessionID instead. It exists only for internal usage by the builders.
func (m *SessionMessageMutation) SessionIDs() (ids []string) {
	if id := m.session; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSession resets all changes to the "session" edge.
func (m *SessionMessageMutation) ResetSession() {
	m.session = nil
	m.clearedsession = false
}

// Where appends a list predicates to the SessionMessageMutation builder.
func (m *SessionMessageMutation) Where(ps ...predicate.SessionMessage) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SessionMessageMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SessionMessageMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SessionMessage, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SessionMessageMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SessionMessageMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SessionMessage).
func (m *SessionMessageMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SessionMessageMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.session != nil {
		fields = append(fields, sessionmessage.FieldSessionID)
	}
	if m.seq != nil {
		fields = append(fields, sessionmessage.FieldSeq)
	}
	if m.role != nil {
		fields = append(fields, sessionmessage.FieldRole)
	}
	if m.content != nil {
		fields = append(fields, sessionmessage.FieldContent)
	}
	if m.tool_calls != nil {
		fields = append(fields, sessionmessage.FieldToolCalls)
	}
	if m.tool_call_id != nil {
		fields = append(fields, sessionmessage.FieldToolCallID)
	}
	if m.create_time != nil {
		fields = append(fields, sessionmessage.FieldCreateTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SessionMessageMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sessionmessage.FieldSessionID:
		return m.SessionID()
	case sessionmessage.FieldSeq:
		return m.Seq()
	case sessionmessage.FieldRole:
		return m.Role()
	case sessionmessage.FieldContent:
		return m.Content()
	case sessionmessage.FieldToolCalls:
		return m.ToolCalls()
	case sessionmessage.FieldToolCallID:
		return m.ToolCallID()
	case sessionmessage.FieldCreateTime:
		return m.CreateTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SessionMessageMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sessionmessage.FieldSessionID:
		return m.OldSessionID(ctx)
	case sessionmessage.FieldSeq:
		return m.OldSeq(ctx)
	case sessionmessage.FieldRole:
		return m.OldRole(ctx)
	case sessionmessage.FieldContent:
		return m.OldContent(ctx)
	case sessionmessage.FieldToolCalls:
		return m.OldToolCalls(ctx)
	case sessionmessage.FieldToolCallID:
		return m.OldToolCallID(ctx)
	case sessionmessage.FieldCreateTime:
		return m.OldCreateTime(ctx)
	}
	return nil, fmt.Errorf("unknown SessionMessage field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SessionMessageMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sessionmessage.FieldSessionID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSessionID(v)
		return nil
	case sessionmessage.FieldSeq:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeq(v)
		return nil
	case sessionmessage.FieldRole:
		v, ok := value.(sessionmessage.Role)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRole(v)
		return nil
	case sessionmessage.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case sessionmessage.FieldToolCalls:
		v, ok := value.([]schema.ToolCall)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToolCalls(v)
		return nil
	case sessionmessage.FieldToolCallID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToolCallID(v)
		return nil
	case sessionmessage.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	}
	return fmt.Errorf("unknown SessionMessage field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SessionMessageMutation) AddedFields() []string {
	var fields []string
	if m.addseq != nil {
		fields = append(fields, sessionmessage.FieldSeq)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SessionMessageMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case sessionmessage.FieldSeq:
		return m.AddedSeq()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SessionMessageMutation) AddField(name string, value ent.Value) error {
	switch name {
	case sessionmessage.FieldSeq:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSeq(v)
		return nil
	}
	return fmt.Errorf("unknown SessionMessage numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SessionMessageMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(sessionmessage.FieldContent) {
		fields = append(fields, sessionmessage.FieldContent)
	}
	if m.FieldCleared(sessionmessage.FieldToolCalls) {
		fields = append(fields, sessionmessage.FieldToolCalls)
	}
	if m.FieldCleared(sessionmessage.FieldToolCallID) {
		fields = append(fields, sessionmessage.FieldToolCallID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SessionMessageMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SessionMessageMutation) ClearField(name string) error {
	switch name {
	case sessionmessage.FieldContent:
		m.ClearContent()
		return nil
	case sessionmessage.FieldToolCalls:
		m.ClearToolCalls()
		return nil
	case sessionmessage.FieldToolCallID:
		m.ClearToolCallID()
		return nil
	}
	return fmt.Errorf("unknown SessionMessage nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SessionMessageMutation) ResetField(name string) error {
	switch name {
	case sessionmessage.FieldSessionID:
		m.ResetSessionID()
		return nil
	case sessionmessage.FieldSeq:
		m.ResetSeq()
		return nil
	case sessionmessage.FieldRole:
		m.ResetRole()
		return nil
	case sessionmessage.FieldContent:
		m.ResetContent()
		return nil
	case sessionmessage.FieldToolCalls:
		m.ResetToolCalls()
		return nil
	case sessionmessage.FieldToolCallID:
		m.ResetToolCallID()
		return nil
	case sessionmessage.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	}
	return fmt.Errorf("unknown SessionMessage field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SessionMessageMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.session != nil {
		edges = append(edges, sessionmessage.EdgeSession)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SessionMessageMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case sessionmessage.EdgeSession:
		if id := m.session; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SessionMessageMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SessionMessageMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SessionMessageMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedsession {
		edges = append(edges, sessionmessage.EdgeSession)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SessionMessageMutation) EdgeCleared(name string) bool {
	switch name {
	case sessionmessage.EdgeSession:
		return m.clearedsession
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SessionMessageMutation) ClearEdge(name string) error {
	switch name {
	case sessionmessage.EdgeSession:
		m.ClearSession()
		return nil
	}
	return fmt.Errorf("unknown SessionMessage unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SessionMessageMutation) ResetEdge(name string) error {
	switch name {
	case sessionmessage.EdgeSession:
		m.ResetSession()
		return nil
	}
	return fmt.Errorf("unknown SessionMessage edge %s", name)
}
