// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/schema"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[2].Descriptor()
	// session.DefaultUserID holds the default value on creation for the user_id field.
	session.DefaultUserID = sessionDescUserID.Default.(int64)
	// sessionDescUsername is the schema descriptor for username field.
	sessionDescUsername := sessionFields[3].Descriptor()
	// session.DefaultUsername holds the default value on creation for the username field.
	session.DefaultUsername = sessionDescUsername.Default.(string)
	// sessionDescBusinessID is the schema descriptor for business_id field.
	sessionDescBusinessID := sessionFields[4].Descriptor()
	// session.DefaultBusinessID holds the default value on creation for the business_id field.
	session.DefaultBusinessID = sessionDescBusinessID.Default.(string)
	// sessionDescBusinessType is the schema descriptor for business_type field.
	sessionDescBusinessType := sessionFields[5].Descriptor()
	// session.DefaultBusinessType holds the default value on creation for the business_type field.
	session.DefaultBusinessType = sessionDescBusinessType.Default.(string)
	// sessionDescBusinessMeta is the schema descriptor for business_meta field.
	sessionDescBusinessMeta := sessionFields[6].Descriptor()
	// session.DefaultBusinessMeta holds the default value on creation for the business_meta field.
	session.DefaultBusinessMeta = sessionDescBusinessMeta.Default.(func() map[string]interface{})
	// sessionDescMode is the schema descriptor for mode field.
	sessionDescMode := sessionFields[7].Descriptor()
	// session.DefaultMode holds the default value on creation for the mode field.
	session.DefaultMode = sessionDescMode.Default.(string)
	// sessionDescHeartbeatInterval is the schema descriptor for heartbeat_interval field.
	sessionDescHeartbeatInterval := sessionFields[8].Descriptor()
	// session.DefaultHeartbeatInterval holds the default value on creation for the heartbeat_interval field.
	session.DefaultHeartbeatInterval = sessionDescHeartbeatInterval.Default.(int)
	// sessionDescSummary is the schema descriptor for summary field.
	sessionDescSummary := sessionFields[9].Descriptor()
	// session.DefaultSummary holds the default value on creation for the summary field.
	session.DefaultSummary = sessionDescSummary.Default.(string)
	// sessionDescLockedBy is the schema descriptor for locked_by field.
	sessionDescLockedBy := sessionFields[10].Descriptor()
	// session.DefaultLockedBy holds the default value on creation for the locked_by field.
	session.DefaultLockedBy = sessionDescLockedBy.Default.(string)
	// sessionDescCreateTime is the schema descriptor for create_time field.
	sessionDescCreateTime := sessionFields[12].Descriptor()
	// session.DefaultCreateTime holds the default value on creation for the create_time field.
	session.DefaultCreateTime = sessionDescCreateTime.Default.(func() time.Time)
	// sessionDescUpdateTime is the schema descriptor for update_time field.
	sessionDescUpdateTime := sessionFields[13].Descriptor()
	// session.DefaultUpdateTime holds the default value on creation for the update_time field.
	session.DefaultUpdateTime = sessionDescUpdateTime.Default.(func() time.Time)
	// session.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	session.UpdateDefaultUpdateTime = sessionDescUpdateTime.UpdateDefault.(func() time.Time)
	sessionmessageFields := schema.SessionMessage{}.Fields()
	_ = sessionmessageFields
	// sessionmessageDescContent is the schema descriptor for content field.
	sessionmessageDescContent := sessionmessageFields[4].Descriptor()
	// sessionmessage.DefaultContent holds the default value on creation for the content field.
	sessionmessage.DefaultContent = sessionmessageDescContent.Default.(string)
	// sessionmessageDescToolCalls is the schema descriptor for tool_calls field.
	sessionmessageDescToolCalls := sessionmessageFields[5].Descriptor()
	// sessionmessage.DefaultToolCalls holds the default value on creation for the tool_calls field.
	sessionmessage.DefaultToolCalls = sessionmessageDescToolCalls.Default.(func() []schema.ToolCall)
	// sessionmessageDescToolCallID is the schema descriptor for tool_call_id field.
	sessionmessageDescToolCallID := sessionmessageFields[6].Descriptor()
	// sessionmessage.DefaultToolCallID holds the default value on creation for the tool_call_id field.
	sessionmessage.DefaultToolCallID = sessionmessageDescToolCallID.Default.(string)
	// sessionmessageDescCreateTime is the schema descriptor for create_time field.
	sessionmessageDescCreateTime := sessionmessageFields[7].Descriptor()
	// sessionmessage.DefaultCreateTime holds the default value on creation for the create_time field.
	sessionmessage.DefaultCreateTime = sessionmessageDescCreateTime.Default.(func() time.Time)
}
