// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/predicate"
	"acp/ent/sessionmessage"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionMessageDelete is the builder for deleting a SessionMessage entity.
type SessionMessageDelete struct {
	config
	hooks    []Hook
	mutation *SessionMessageMutation
}

// Where appends a list predicates to the SessionMessageDelete builder.
func (_d *SessionMessageDelete) Where(ps ...predicate.SessionMessage) *SessionMessageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SessionMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SessionMessageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SessionMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sessionmessage.Table, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SessionMessageDeleteOne is the builder for deleting a single SessionMessage entity.
type SessionMessageDeleteOne struct {
	_d *SessionMessageDelete
}

// Where appends a list predicates to the SessionMessageDelete builder.
func (_d *SessionMessageDeleteOne) Where(ps ...predicate.SessionMessage) *SessionMessageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SessionMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sessionmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SessionMessageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
