// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *SessionCreate) SetStatus(v session.Status) *SessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SessionCreate) SetNillableStatus(v *session.Status) *SessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SessionCreate) SetUserID(v int64) *SessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUserID(v *int64) *SessionCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *SessionCreate) SetUsername(v string) *SessionCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUsername(v *string) *SessionCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetBusinessID sets the "business_id" field.
func (_c *SessionCreate) SetBusinessID(v string) *SessionCreate {
	_c.mutation.SetBusinessID(v)
	return _c
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableBusinessID(v *string) *SessionCreate {
	if v != nil {
		_c.SetBusinessID(*v)
	}
	return _c
}

// SetBusinessType sets the "business_type" field.
func (_c *SessionCreate) SetBusinessType(v string) *SessionCreate {
	_c.mutation.SetBusinessType(v)
	return _c
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_c *SessionCreate) SetNillableBusinessType(v *string) *SessionCreate {
	if v != nil {
		_c.SetBusinessType(*v)
	}
	return _c
}

// SetBusinessMeta sets the "business_meta" field.
func (_c *SessionCreate) SetBusinessMeta(v map[string]interface{}) *SessionCreate {
	_c.mutation.SetBusinessMeta(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *SessionCreate) SetMode(v string) *SessionCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *SessionCreate) SetNillableMode(v *string) *SessionCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *SessionCreate) SetSummary(v string) *SessionCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *SessionCreate) SetNillableSummary(v *string) *SessionCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SessionCreate) SetCreateTime(v time.Time) *SessionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCreateTime(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SessionCreate) SetUpdateTime(v time.Time) *SessionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUpdateTime(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v string) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMessageIDs adds the "messages" edge to the SessionMessage entity by IDs.
func (_c *SessionCreate) AddMessageIDs(ids ...int64) *SessionCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the SessionMessage entity.
func (_c *SessionCreate) AddMessages(v ...*SessionMessage) *SessionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := session.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UserID(); !ok {
		v := session.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := session.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.BusinessID(); !ok {
		v := session.DefaultBusinessID
		_c.mutation.SetBusinessID(v)
	}
	if _, ok := _c.mutation.BusinessType(); !ok {
		v := session.DefaultBusinessType
		_c.mutation.SetBusinessType(v)
	}
	if _, ok := _c.mutation.BusinessMeta(); !ok {
		v := session.DefaultBusinessMeta()
		_c.mutation.SetBusinessMeta(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := session.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := session.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := session.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := session.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Session.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := session.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Session.mode"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Session.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Session.update_time"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(session.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.BusinessID(); ok {
		_spec.SetField(session.FieldBusinessID, field.TypeString, value)
		_node.BusinessID = value
	}
	if value, ok := _c.mutation.BusinessType(); ok {
		_spec.SetField(session.FieldBusinessType, field.TypeString, value)
		_node.BusinessType = value
	}
	if value, ok := _c.mutation.BusinessMeta(); ok {
		_spec.SetField(session.FieldBusinessMeta, field.TypeJSON, value)
		_node.BusinessMeta = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(session.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(session.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(session.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(session.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
