// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/schema"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SessionMessage is the model entity for the SessionMessage schema.
type SessionMessage struct {
	config `json:"-"`
	// ID of the ent.
	// Auto-increment message ID
	ID int64 `json:"id,omitempty"`
	// Foreign key to Session
	SessionID string `json:"session_id,omitempty"`
	// Message sequence number within the session
	Seq int `json:"seq,omitempty"`
	// Message role
	Role sessionmessage.Role `json:"role,omitempty"`
	// Message text content
	Content string `json:"content,omitempty"`
	// Assistant tool calls (only for role=assistant)
	ToolCalls []schema.ToolCall `json:"tool_calls,omitempty"`
	// Tool call ID for matching tool result to call (only for role=tool)
	ToolCallID string `json:"tool_call_id,omitempty"`
	// Message creation timestamp
	CreateTime time.Time `json:"create_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SessionMessageQuery when eager-loading is set.
	Edges        SessionMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SessionMessageEdges holds the relations/edges for other nodes in the graph.
type SessionMessageEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionMessageEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SessionMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sessionmessage.FieldToolCalls:
			values[i] = new([]byte)
		case sessionmessage.FieldID, sessionmessage.FieldSeq:
			values[i] = new(sql.NullInt64)
		case sessionmessage.FieldSessionID, sessionmessage.FieldRole, sessionmessage.FieldContent, sessionmessage.FieldToolCallID:
			values[i] = new(sql.NullString)
		case sessionmessage.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SessionMessage fields.
func (_m *SessionMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sessionmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sessionmessage.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case sessionmessage.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = int(value.Int64)
			}
		case sessionmessage.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = sessionmessage.Role(value.String)
			}
		case sessionmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case sessionmessage.FieldToolCalls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tool_calls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ToolCalls); err != nil {
					return fmt.Errorf("unmarshal field tool_calls: %w", err)
				}
			}
		case sessionmessage.FieldToolCallID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool_call_id", values[i])
			} else if value.Valid {
				_m.ToolCallID = value.String
			}
		case sessionmessage.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SessionMessage.
// This includes values selected through modifiers, order, etc.
func (_m *SessionMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the SessionMessage entity.
func (_m *SessionMessage) QuerySession() *SessionQuery {
	return NewSessionMessageClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this SessionMessage.
// Note that you need to call SessionMessage.Unwrap() before calling this method if this SessionMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SessionMessage) Update() *SessionMessageUpdateOne {
	return NewSessionMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SessionMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SessionMessage) Unwrap() *SessionMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SessionMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SessionMessage) String() string {
	var builder strings.Builder
	builder.WriteString("SessionMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("tool_calls=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolCalls))
	builder.WriteString(", ")
	builder.WriteString("tool_call_id=")
	builder.WriteString(_m.ToolCallID)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SessionMessages is a parsable slice of SessionMessage.
type SessionMessages []*SessionMessage
