// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/predicate"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionUpdate) SetStatus(v session.Status) *SessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableStatus(v *session.Status) *SessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdate) SetUserID(v int64) *SessionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserID(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SessionUpdate) AddUserID(v int64) *SessionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdate) ClearUserID() *SessionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *SessionUpdate) SetUsername(v string) *SessionUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUsername(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *SessionUpdate) ClearUsername() *SessionUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetBusinessID sets the "business_id" field.
func (_u *SessionUpdate) SetBusinessID(v string) *SessionUpdate {
	_u.mutation.SetBusinessID(v)
	return _u
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableBusinessID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetBusinessID(*v)
	}
	return _u
}

// ClearBusinessID clears the value of the "business_id" field.
func (_u *SessionUpdate) ClearBusinessID() *SessionUpdate {
	_u.mutation.ClearBusinessID()
	return _u
}

// SetBusinessType sets the "business_type" field.
func (_u *SessionUpdate) SetBusinessType(v string) *SessionUpdate {
	_u.mutation.SetBusinessType(v)
	return _u
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableBusinessType(v *string) *SessionUpdate {
	if v != nil {
		_u.SetBusinessType(*v)
	}
	return _u
}

// ClearBusinessType clears the value of the "business_type" field.
func (_u *SessionUpdate) ClearBusinessType() *SessionUpdate {
	_u.mutation.ClearBusinessType()
	return _u
}

// SetBusinessMeta sets the "business_meta" field.
func (_u *SessionUpdate) SetBusinessMeta(v map[string]interface{}) *SessionUpdate {
	_u.mutation.SetBusinessMeta(v)
	return _u
}

// ClearBusinessMeta clears the value of the "business_meta" field.
func (_u *SessionUpdate) ClearBusinessMeta() *SessionUpdate {
	_u.mutation.ClearBusinessMeta()
	return _u
}

// SetHeartbeatInterval sets the "heartbeat_interval" field.
func (_u *SessionUpdate) SetHeartbeatInterval(v int) *SessionUpdate {
	_u.mutation.ResetHeartbeatInterval()
	_u.mutation.SetHeartbeatInterval(v)
	return _u
}

// SetNillableHeartbeatInterval sets the "heartbeat_interval" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableHeartbeatInterval(v *int) *SessionUpdate {
	if v != nil {
		_u.SetHeartbeatInterval(*v)
	}
	return _u
}

// AddHeartbeatInterval adds value to the "heartbeat_interval" field.
func (_u *SessionUpdate) AddHeartbeatInterval(v int) *SessionUpdate {
	_u.mutation.AddHeartbeatInterval(v)
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SessionUpdate) SetSummary(v string) *SessionUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableSummary(v *string) *SessionUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SessionUpdate) ClearSummary() *SessionUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *SessionUpdate) SetLockedBy(v string) *SessionUpdate {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLockedBy(v *string) *SessionUpdate {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *SessionUpdate) ClearLockedBy() *SessionUpdate {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *SessionUpdate) SetLockedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLockedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *SessionUpdate) ClearLockedAt() *SessionUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SessionUpdate) SetUpdateTime(v time.Time) *SessionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// AddMessageIDs adds the "messages" edge to the SessionMessage entity by IDs.
func (_u *SessionUpdate) AddMessageIDs(ids ...int64) *SessionUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SessionMessage entity.
func (_u *SessionUpdate) AddMessages(v ...*SessionMessage) *SessionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the SessionMessage entity.
func (_u *SessionUpdate) ClearMessages() *SessionUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SessionMessage entities by IDs.
func (_u *SessionUpdate) RemoveMessageIDs(ids ...int64) *SessionUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SessionMessage entities.
func (_u *SessionUpdate) RemoveMessages(v ...*SessionMessage) *SessionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := session.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := session.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(session.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(session.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(session.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.BusinessID(); ok {
		_spec.SetField(session.FieldBusinessID, field.TypeString, value)
	}
	if _u.mutation.BusinessIDCleared() {
		_spec.ClearField(session.FieldBusinessID, field.TypeString)
	}
	if value, ok := _u.mutation.BusinessType(); ok {
		_spec.SetField(session.FieldBusinessType, field.TypeString, value)
	}
	if _u.mutation.BusinessTypeCleared() {
		_spec.ClearField(session.FieldBusinessType, field.TypeString)
	}
	if value, ok := _u.mutation.BusinessMeta(); ok {
		_spec.SetField(session.FieldBusinessMeta, field.TypeJSON, value)
	}
	if _u.mutation.BusinessMetaCleared() {
		_spec.ClearField(session.FieldBusinessMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.HeartbeatInterval(); ok {
		_spec.SetField(session.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeartbeatInterval(); ok {
		_spec.AddField(session.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(session.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(session.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(session.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(session.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(session.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(session.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(session.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetStatus sets the "status" field.
func (_u *SessionUpdateOne) SetStatus(v session.Status) *SessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableStatus(v *session.Status) *SessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdateOne) SetUserID(v int64) *SessionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserID(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SessionUpdateOne) AddUserID(v int64) *SessionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdateOne) ClearUserID() *SessionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *SessionUpdateOne) SetUsername(v string) *SessionUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUsername(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *SessionUpdateOne) ClearUsername() *SessionUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetBusinessID sets the "business_id" field.
func (_u *SessionUpdateOne) SetBusinessID(v string) *SessionUpdateOne {
	_u.mutation.SetBusinessID(v)
	return _u
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableBusinessID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetBusinessID(*v)
	}
	return _u
}

// ClearBusinessID clears the value of the "business_id" field.
func (_u *SessionUpdateOne) ClearBusinessID() *SessionUpdateOne {
	_u.mutation.ClearBusinessID()
	return _u
}

// SetBusinessType sets the "business_type" field.
func (_u *SessionUpdateOne) SetBusinessType(v string) *SessionUpdateOne {
	_u.mutation.SetBusinessType(v)
	return _u
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableBusinessType(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetBusinessType(*v)
	}
	return _u
}

// ClearBusinessType clears the value of the "business_type" field.
func (_u *SessionUpdateOne) ClearBusinessType() *SessionUpdateOne {
	_u.mutation.ClearBusinessType()
	return _u
}

// SetBusinessMeta sets the "business_meta" field.
func (_u *SessionUpdateOne) SetBusinessMeta(v map[string]interface{}) *SessionUpdateOne {
	_u.mutation.SetBusinessMeta(v)
	return _u
}

// ClearBusinessMeta clears the value of the "business_meta" field.
func (_u *SessionUpdateOne) ClearBusinessMeta() *SessionUpdateOne {
	_u.mutation.ClearBusinessMeta()
	return _u
}

// SetHeartbeatInterval sets the "heartbeat_interval" field.
func (_u *SessionUpdateOne) SetHeartbeatInterval(v int) *SessionUpdateOne {
	_u.mutation.ResetHeartbeatInterval()
	_u.mutation.SetHeartbeatInterval(v)
	return _u
}

// SetNillableHeartbeatInterval sets the "heartbeat_interval" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableHeartbeatInterval(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetHeartbeatInterval(*v)
	}
	return _u
}

// AddHeartbeatInterval adds value to the "heartbeat_interval" field.
func (_u *SessionUpdateOne) AddHeartbeatInterval(v int) *SessionUpdateOne {
	_u.mutation.AddHeartbeatInterval(v)
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SessionUpdateOne) SetSummary(v string) *SessionUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableSummary(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SessionUpdateOne) ClearSummary() *SessionUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *SessionUpdateOne) SetLockedBy(v string) *SessionUpdateOne {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLockedBy(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *SessionUpdateOne) ClearLockedBy() *SessionUpdateOne {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *SessionUpdateOne) SetLockedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLockedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *SessionUpdateOne) ClearLockedAt() *SessionUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SessionUpdateOne) SetUpdateTime(v time.Time) *SessionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// AddMessageIDs adds the "messages" edge to the SessionMessage entity by IDs.
func (_u *SessionUpdateOne) AddMessageIDs(ids ...int64) *SessionUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SessionMessage entity.
func (_u *SessionUpdateOne) AddMessages(v ...*SessionMessage) *SessionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the SessionMessage entity.
func (_u *SessionUpdateOne) ClearMessages() *SessionUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SessionMessage entities by IDs.
func (_u *SessionUpdateOne) RemoveMessageIDs(ids ...int64) *SessionUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SessionMessage entities.
func (_u *SessionUpdateOne) RemoveMessages(v ...*SessionMessage) *SessionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := session.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := session.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(session.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(session.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(session.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.BusinessID(); ok {
		_spec.SetField(session.FieldBusinessID, field.TypeString, value)
	}
	if _u.mutation.BusinessIDCleared() {
		_spec.ClearField(session.FieldBusinessID, field.TypeString)
	}
	if value, ok := _u.mutation.BusinessType(); ok {
		_spec.SetField(session.FieldBusinessType, field.TypeString, value)
	}
	if _u.mutation.BusinessTypeCleared() {
		_spec.ClearField(session.FieldBusinessType, field.TypeString)
	}
	if value, ok := _u.mutation.BusinessMeta(); ok {
		_spec.SetField(session.FieldBusinessMeta, field.TypeJSON, value)
	}
	if _u.mutation.BusinessMetaCleared() {
		_spec.ClearField(session.FieldBusinessMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.HeartbeatInterval(); ok {
		_spec.SetField(session.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeartbeatInterval(); ok {
		_spec.AddField(session.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(session.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(session.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(session.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(session.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(session.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(session.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(session.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.MessagesTable,
			Columns: []string{session.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
