// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/predicate"
	"acp/ent/schema"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SessionMessageUpdate is the builder for updating SessionMessage entities.
type SessionMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMessageMutation
}

// Where appends a list predicates to the SessionMessageUpdate builder.
func (_u *SessionMessageUpdate) Where(ps ...predicate.SessionMessage) *SessionMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SessionMessageUpdate) SetSessionID(v string) *SessionMessageUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableSessionID(v *string) *SessionMessageUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *SessionMessageUpdate) SetSeq(v int) *SessionMessageUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableSeq(v *int) *SessionMessageUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *SessionMessageUpdate) AddSeq(v int) *SessionMessageUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *SessionMessageUpdate) SetRole(v sessionmessage.Role) *SessionMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableRole(v *sessionmessage.Role) *SessionMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SessionMessageUpdate) SetContent(v string) *SessionMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableContent(v *string) *SessionMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *SessionMessageUpdate) ClearContent() *SessionMessageUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetToolCalls sets the "tool_calls" field.
func (_u *SessionMessageUpdate) SetToolCalls(v []schema.ToolCall) *SessionMessageUpdate {
	_u.mutation.SetToolCalls(v)
	return _u
}

// AppendToolCalls appends value to the "tool_calls" field.
func (_u *SessionMessageUpdate) AppendToolCalls(v []schema.ToolCall) *SessionMessageUpdate {
	_u.mutation.AppendToolCalls(v)
	return _u
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (_u *SessionMessageUpdate) ClearToolCalls() *SessionMessageUpdate {
	_u.mutation.ClearToolCalls()
	return _u
}

// SetToolCallID sets the "tool_call_id" field.
func (_u *SessionMessageUpdate) SetToolCallID(v string) *SessionMessageUpdate {
	_u.mutation.SetToolCallID(v)
	return _u
}

// SetNillableToolCallID sets the "tool_call_id" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableToolCallID(v *string) *SessionMessageUpdate {
	if v != nil {
		_u.SetToolCallID(*v)
	}
	return _u
}

// ClearToolCallID clears the value of the "tool_call_id" field.
func (_u *SessionMessageUpdate) ClearToolCallID() *SessionMessageUpdate {
	_u.mutation.ClearToolCallID()
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *SessionMessageUpdate) SetSession(v *Session) *SessionMessageUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the SessionMessageMutation object of the builder.
func (_u *SessionMessageUpdate) Mutation() *SessionMessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *SessionMessageUpdate) ClearSession() *SessionMessageUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionMessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := sessionmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SessionMessage.role": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionMessage.session"`)
	}
	return nil
}

func (_u *SessionMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionmessage.Table, sessionmessage.Columns, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(sessionmessage.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(sessionmessage.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(sessionmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(sessionmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(sessionmessage.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ToolCalls(); ok {
		_spec.SetField(sessionmessage.FieldToolCalls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedToolCalls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sessionmessage.FieldToolCalls, value)
		})
	}
	if _u.mutation.ToolCallsCleared() {
		_spec.ClearField(sessionmessage.FieldToolCalls, field.TypeJSON)
	}
	if value, ok := _u.mutation.ToolCallID(); ok {
		_spec.SetField(sessionmessage.FieldToolCallID, field.TypeString, value)
	}
	if _u.mutation.ToolCallIDCleared() {
		_spec.ClearField(sessionmessage.FieldToolCallID, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionMessageUpdateOne is the builder for updating a single SessionMessage entity.
type SessionMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMessageMutation
}

// SetSessionID sets the "session_id" field.
func (_u *SessionMessageUpdateOne) SetSessionID(v string) *SessionMessageUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableSessionID(v *string) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *SessionMessageUpdateOne) SetSeq(v int) *SessionMessageUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableSeq(v *int) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *SessionMessageUpdateOne) AddSeq(v int) *SessionMessageUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *SessionMessageUpdateOne) SetRole(v sessionmessage.Role) *SessionMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableRole(v *sessionmessage.Role) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SessionMessageUpdateOne) SetContent(v string) *SessionMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableContent(v *string) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *SessionMessageUpdateOne) ClearContent() *SessionMessageUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetToolCalls sets the "tool_calls" field.
func (_u *SessionMessageUpdateOne) SetToolCalls(v []schema.ToolCall) *SessionMessageUpdateOne {
	_u.mutation.SetToolCalls(v)
	return _u
}

// AppendToolCalls appends value to the "tool_calls" field.
func (_u *SessionMessageUpdateOne) AppendToolCalls(v []schema.ToolCall) *SessionMessageUpdateOne {
	_u.mutation.AppendToolCalls(v)
	return _u
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (_u *SessionMessageUpdateOne) ClearToolCalls() *SessionMessageUpdateOne {
	_u.mutation.ClearToolCalls()
	return _u
}

// SetToolCallID sets the "tool_call_id" field.
func (_u *SessionMessageUpdateOne) SetToolCallID(v string) *SessionMessageUpdateOne {
	_u.mutation.SetToolCallID(v)
	return _u
}

// SetNillableToolCallID sets the "tool_call_id" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableToolCallID(v *string) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetToolCallID(*v)
	}
	return _u
}

// ClearToolCallID clears the value of the "tool_call_id" field.
func (_u *SessionMessageUpdateOne) ClearToolCallID() *SessionMessageUpdateOne {
	_u.mutation.ClearToolCallID()
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *SessionMessageUpdateOne) SetSession(v *Session) *SessionMessageUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the SessionMessageMutation object of the builder.
func (_u *SessionMessageUpdateOne) Mutation() *SessionMessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *SessionMessageUpdateOne) ClearSession() *SessionMessageUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the SessionMessageUpdate builder.
func (_u *SessionMessageUpdateOne) Where(ps ...predicate.SessionMessage) *SessionMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionMessageUpdateOne) Select(field string, fields ...string) *SessionMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SessionMessage entity.
func (_u *SessionMessageUpdateOne) Save(ctx context.Context) (*SessionMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionMessageUpdateOne) SaveX(ctx context.Context) *SessionMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := sessionmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SessionMessage.role": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionMessage.session"`)
	}
	return nil
}

func (_u *SessionMessageUpdateOne) sqlSave(ctx context.Context) (_node *SessionMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionmessage.Table, sessionmessage.Columns, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SessionMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionmessage.FieldID)
		for _, f := range fields {
			if !sessionmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sessionmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(sessionmessage.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(sessionmessage.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(sessionmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(sessionmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(sessionmessage.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ToolCalls(); ok {
		_spec.SetField(sessionmessage.FieldToolCalls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedToolCalls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sessionmessage.FieldToolCalls, value)
		})
	}
	if _u.mutation.ToolCallsCleared() {
		_spec.ClearField(sessionmessage.FieldToolCalls, field.TypeJSON)
	}
	if value, ok := _u.mutation.ToolCallID(); ok {
		_spec.SetField(sessionmessage.FieldToolCallID, field.TypeString, value)
	}
	if _u.mutation.ToolCallIDCleared() {
		_spec.ClearField(sessionmessage.FieldToolCallID, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SessionMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
