// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/predicate"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionMessageQuery is the builder for querying SessionMessage entities.
type SessionMessageQuery struct {
	config
	ctx         *QueryContext
	order       []sessionmessage.OrderOption
	inters      []Interceptor
	predicates  []predicate.SessionMessage
	withSession *SessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SessionMessageQuery builder.
func (_q *SessionMessageQuery) Where(ps ...predicate.SessionMessage) *SessionMessageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SessionMessageQuery) Limit(limit int) *SessionMessageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SessionMessageQuery) Offset(offset int) *SessionMessageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SessionMessageQuery) Unique(unique bool) *SessionMessageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SessionMessageQuery) Order(o ...sessionmessage.OrderOption) *SessionMessageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySession chains the current query on the "session" edge.
func (_q *SessionMessageQuery) QuerySession() *SessionQuery {
	query := (&SessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sessionmessage.Table, sessionmessage.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sessionmessage.SessionTable, sessionmessage.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SessionMessage entity from the query.
// Returns a *NotFoundError when no SessionMessage was found.
func (_q *SessionMessageQuery) First(ctx context.Context) (*SessionMessage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sessionmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SessionMessageQuery) FirstX(ctx context.Context) *SessionMessage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SessionMessage ID from the query.
// Returns a *NotFoundError when no SessionMessage ID was found.
func (_q *SessionMessageQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sessionmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SessionMessageQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SessionMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SessionMessage entity is found.
// Returns a *NotFoundError when no SessionMessage entities are found.
func (_q *SessionMessageQuery) Only(ctx context.Context) (*SessionMessage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sessionmessage.Label}
	default:
		return nil, &NotSingularError{sessionmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SessionMessageQuery) OnlyX(ctx context.Context) *SessionMessage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SessionMessage ID in the query.
// Returns a *NotSingularError when more than one SessionMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SessionMessageQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sessionmessage.Label}
	default:
		err = &NotSingularError{sessionmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SessionMessageQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SessionMessages.
func (_q *SessionMessageQuery) All(ctx context.Context) ([]*SessionMessage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SessionMessage, *SessionMessageQuery]()
	return withInterceptors[[]*SessionMessage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SessionMessageQuery) AllX(ctx context.Context) []*SessionMessage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SessionMessage IDs.
func (_q *SessionMessageQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sessionmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SessionMessageQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SessionMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SessionMessageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SessionMessageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SessionMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SessionMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SessionMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SessionMessageQuery) Clone() *SessionMessageQuery {
	if _q == nil {
		return nil
	}
	return &SessionMessageQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]sessionmessage.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.SessionMessage{}, _q.predicates...),
		withSession: _q.withSession.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SessionMessageQuery) WithSession(opts ...func(*SessionQuery)) *SessionMessageQuery {
	query := (&SessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSession = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SessionMessage.Query().
//		GroupBy(sessionmessage.FieldSessionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SessionMessageQuery) GroupBy(field string, fields ...string) *SessionMessageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SessionMessageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sessionmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//	}
//
//	client.SessionMessage.Query().
//		Select(sessionmessage.FieldSessionID).
//		Scan(ctx, &v)
func (_q *SessionMessageQuery) Select(fields ...string) *SessionMessageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SessionMessageSelect{SessionMessageQuery: _q}
	sbuild.label = sessionmessage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SessionMessageSelect configured with the given aggregations.
func (_q *SessionMessageQuery) Aggregate(fns ...AggregateFunc) *SessionMessageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SessionMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sessionmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SessionMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SessionMessage, error) {
	var (
		nodes       = []*SessionMessage{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSession != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SessionMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SessionMessage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSession; query != nil {
		if err := _q.loadSession(ctx, query, nodes, nil,
			func(n *SessionMessage, e *Session) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SessionMessageQuery) loadSession(ctx context.Context, query *SessionQuery, nodes []*SessionMessage, init func(*SessionMessage), assign func(*SessionMessage, *Session)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SessionMessage)
	for i := range nodes {
		fk := nodes[i].SessionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(session.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SessionMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SessionMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sessionmessage.Table, sessionmessage.Columns, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionmessage.FieldID)
		for i := range fields {
			if fields[i] != sessionmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSession != nil {
			_spec.Node.AddColumnOnce(sessionmessage.FieldSessionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SessionMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sessionmessage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sessionmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SessionMessageGroupBy is the group-by builder for SessionMessage entities.
type SessionMessageGroupBy struct {
	selector
	build *SessionMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SessionMessageGroupBy) Aggregate(fns ...AggregateFunc) *SessionMessageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SessionMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionMessageQuery, *SessionMessageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SessionMessageGroupBy) sqlScan(ctx context.Context, root *SessionMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SessionMessageSelect is the builder for selecting fields of SessionMessage entities.
type SessionMessageSelect struct {
	*SessionMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SessionMessageSelect) Aggregate(fns ...AggregateFunc) *SessionMessageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SessionMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionMessageQuery, *SessionMessageSelect](ctx, _s.SessionMessageQuery, _s, _s.inters, v)
}

func (_s *SessionMessageSelect) sqlScan(ctx context.Context, root *SessionMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
