// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/session"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Session is the model entity for the Session schema.
type Session struct {
	config `json:"-"`
	// ID of the ent.
	// Session unique ID (UUID v4, server-generated)
	ID string `json:"id,omitempty"`
	// Session status: active | idle | closed
	Status session.Status `json:"status,omitempty"`
	// Authenticated user ID
	UserID int64 `json:"user_id,omitempty"`
	// Authenticated username
	Username string `json:"username,omitempty"`
	// Business context identifier
	BusinessID string `json:"business_id,omitempty"`
	// Business context type (e.g., project, workspace)
	BusinessType string `json:"business_type,omitempty"`
	// Extensible business metadata
	BusinessMeta map[string]interface{} `json:"business_meta,omitempty"`
	// Execution mode: agent | plan. Immutable after creation.
	Mode string `json:"mode,omitempty"`
	// Client heartbeat interval in seconds, server timeout = 3x this value
	HeartbeatInterval int `json:"heartbeat_interval,omitempty"`
	// Conversation summary, updated by summarization middleware
	Summary string `json:"summary,omitempty"`
	// Connection ID that currently owns this session
	LockedBy string `json:"locked_by,omitempty"`
	// When the session was locked by the current owner
	LockedAt time.Time `json:"locked_at,omitempty"`
	// Session creation timestamp
	CreateTime time.Time `json:"create_time,omitempty"`
	// Session last update timestamp
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SessionQuery when eager-loading is set.
	Edges        SessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SessionEdges holds the relations/edges for other nodes in the graph.
type SessionEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*SessionMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e SessionEdges) MessagesOrErr() ([]*SessionMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Session) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case session.FieldBusinessMeta:
			values[i] = new([]byte)
		case session.FieldUserID, session.FieldHeartbeatInterval:
			values[i] = new(sql.NullInt64)
		case session.FieldID, session.FieldStatus, session.FieldUsername, session.FieldBusinessID, session.FieldBusinessType, session.FieldMode, session.FieldSummary, session.FieldLockedBy:
			values[i] = new(sql.NullString)
		case session.FieldLockedAt, session.FieldCreateTime, session.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Session fields.
func (_m *Session) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case session.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case session.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = session.Status(value.String)
			}
		case session.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case session.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case session.FieldBusinessID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_id", values[i])
			} else if value.Valid {
				_m.BusinessID = value.String
			}
		case session.FieldBusinessType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_type", values[i])
			} else if value.Valid {
				_m.BusinessType = value.String
			}
		case session.FieldBusinessMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field business_meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BusinessMeta); err != nil {
					return fmt.Errorf("unmarshal field business_meta: %w", err)
				}
			}
		case session.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case session.FieldHeartbeatInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field heartbeat_interval", values[i])
			} else if value.Valid {
				_m.HeartbeatInterval = int(value.Int64)
			}
		case session.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case session.FieldLockedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locked_by", values[i])
			} else if value.Valid {
				_m.LockedBy = value.String
			}
		case session.FieldLockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_at", values[i])
			} else if value.Valid {
				_m.LockedAt = value.Time
			}
		case session.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case session.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Session.
// This includes values selected through modifiers, order, etc.
func (_m *Session) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the Session entity.
func (_m *Session) QueryMessages() *SessionMessageQuery {
	return NewSessionClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this Session.
// Note that you need to call Session.Unwrap() before calling this method if this Session
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Session) Update() *SessionUpdateOne {
	return NewSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Session entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Session) Unwrap() *Session {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Session is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Session) String() string {
	var builder strings.Builder
	builder.WriteString("Session(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("business_id=")
	builder.WriteString(_m.BusinessID)
	builder.WriteString(", ")
	builder.WriteString("business_type=")
	builder.WriteString(_m.BusinessType)
	builder.WriteString(", ")
	builder.WriteString("business_meta=")
	builder.WriteString(fmt.Sprintf("%v", _m.BusinessMeta))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("heartbeat_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.HeartbeatInterval))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("locked_by=")
	builder.WriteString(_m.LockedBy)
	builder.WriteString(", ")
	builder.WriteString("locked_at=")
	builder.WriteString(_m.LockedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Sessions is a parsable slice of Session.
type Sessions []*Session
