// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acp/ent/schema"
	"acp/ent/session"
	"acp/ent/sessionmessage"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionMessageCreate is the builder for creating a SessionMessage entity.
type SessionMessageCreate struct {
	config
	mutation *SessionMessageMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *SessionMessageCreate) SetSessionID(v string) *SessionMessageCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetSeq sets the "seq" field.
func (_c *SessionMessageCreate) SetSeq(v int) *SessionMessageCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *SessionMessageCreate) SetRole(v sessionmessage.Role) *SessionMessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SessionMessageCreate) SetContent(v string) *SessionMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *SessionMessageCreate) SetNillableContent(v *string) *SessionMessageCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetToolCalls sets the "tool_calls" field.
func (_c *SessionMessageCreate) SetToolCalls(v []schema.ToolCall) *SessionMessageCreate {
	_c.mutation.SetToolCalls(v)
	return _c
}

// SetToolCallID sets the "tool_call_id" field.
func (_c *SessionMessageCreate) SetToolCallID(v string) *SessionMessageCreate {
	_c.mutation.SetToolCallID(v)
	return _c
}

// SetNillableToolCallID sets the "tool_call_id" field if the given value is not nil.
func (_c *SessionMessageCreate) SetNillableToolCallID(v *string) *SessionMessageCreate {
	if v != nil {
		_c.SetToolCallID(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SessionMessageCreate) SetCreateTime(v time.Time) *SessionMessageCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SessionMessageCreate) SetNillableCreateTime(v *time.Time) *SessionMessageCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionMessageCreate) SetID(v int64) *SessionMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *SessionMessageCreate) SetSession(v *Session) *SessionMessageCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the SessionMessageMutation object of the builder.
func (_c *SessionMessageCreate) Mutation() *SessionMessageMutation {
	return _c.mutation
}

// Save creates the SessionMessage in the database.
func (_c *SessionMessageCreate) Save(ctx context.Context) (*SessionMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionMessageCreate) SaveX(ctx context.Context) *SessionMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionMessageCreate) defaults() {
	if _, ok := _c.mutation.Content(); !ok {
		v := sessionmessage.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.ToolCalls(); !ok {
		v := sessionmessage.DefaultToolCalls()
		_c.mutation.SetToolCalls(v)
	}
	if _, ok := _c.mutation.ToolCallID(); !ok {
		v := sessionmessage.DefaultToolCallID
		_c.mutation.SetToolCallID(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := sessionmessage.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionMessageCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "SessionMessage.session_id"`)}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "SessionMessage.seq"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "SessionMessage.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := sessionmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SessionMessage.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "SessionMessage.create_time"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "SessionMessage.session"`)}
	}
	return nil
}

func (_c *SessionMessageCreate) sqlSave(ctx context.Context) (*SessionMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionMessageCreate) createSpec() (*SessionMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &SessionMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sessionmessage.Table, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(sessionmessage.FieldSeq, field.TypeInt, value)
		_node.Seq = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(sessionmessage.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(sessionmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ToolCalls(); ok {
		_spec.SetField(sessionmessage.FieldToolCalls, field.TypeJSON, value)
		_node.ToolCalls = value
	}
	if value, ok := _c.mutation.ToolCallID(); ok {
		_spec.SetField(sessionmessage.FieldToolCallID, field.TypeString, value)
		_node.ToolCallID = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(sessionmessage.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionMessageCreateBulk is the builder for creating many SessionMessage entities in bulk.
type SessionMessageCreateBulk struct {
	config
	err      error
	builders []*SessionMessageCreate
}

// Save creates the SessionMessage entities in the database.
func (_c *SessionMessageCreateBulk) Save(ctx context.Context) ([]*SessionMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SessionMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionMessageCreateBulk) SaveX(ctx context.Context) []*SessionMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
