// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SessionMessage is the predicate function for sessionmessage builders.
type SessionMessage func(*sql.Selector)
